// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: distribution.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRevenueDistribution = `-- name: CreateRevenueDistribution :one
INSERT INTO revenue_distributions
    (period, total_revenue, pool_rate, investor_share_rate, investor_pool, dividend_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, period, total_revenue, pool_rate, investor_share_rate, investor_pool, dividend_id, created_by, created_at
`

type CreateRevenueDistributionParams struct {
	Period            string        `json:"period"`
	TotalRevenue      int64         `json:"total_revenue"`
	PoolRate          float64       `json:"pool_rate"`
	InvestorShareRate float64       `json:"investor_share_rate"`
	InvestorPool      int64         `json:"investor_pool"`
	DividendID        uuid.NullUUID `json:"dividend_id"`
	CreatedBy         uuid.UUID     `json:"created_by"`
}

func (q *Queries) CreateRevenueDistribution(ctx context.Context, arg CreateRevenueDistributionParams) (RevenueDistribution, error) {
	row := q.db.QueryRow(ctx, createRevenueDistribution,
		arg.Period,
		arg.TotalRevenue,
		arg.PoolRate,
		arg.InvestorShareRate,
		arg.InvestorPool,
		arg.DividendID,
		arg.CreatedBy,
	)
	var i RevenueDistribution
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.TotalRevenue,
		&i.PoolRate,
		&i.InvestorShareRate,
		&i.InvestorPool,
		&i.DividendID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRevenueDistribution = `-- name: GetRevenueDistribution :one
SELECT id, period, total_revenue, pool_rate, investor_share_rate, investor_pool, dividend_id, created_by, created_at FROM revenue_distributions WHERE id = $1
`

func (q *Queries) GetRevenueDistribution(ctx context.Context, id uuid.UUID) (RevenueDistribution, error) {
	row := q.db.QueryRow(ctx, getRevenueDistribution, id)
	var i RevenueDistribution
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.TotalRevenue,
		&i.PoolRate,
		&i.InvestorShareRate,
		&i.InvestorPool,
		&i.DividendID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRevenueDistribution = `-- name: DeleteRevenueDistribution :exec
DELETE FROM revenue_distributions WHERE id = $1
`

func (q *Queries) DeleteRevenueDistribution(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRevenueDistribution, id)
	return err
}

const deleteRevenueDistributionsByDividend = `-- name: DeleteRevenueDistributionsByDividend :exec
DELETE FROM revenue_distributions WHERE dividend_id = $1
`

func (q *Queries) DeleteRevenueDistributionsByDividend(ctx context.Context, dividendID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteRevenueDistributionsByDividend, dividendID)
	return err
}

const createWithdrawal = `-- name: CreateWithdrawal :one
INSERT INTO withdrawals (user_id, amount, note, source) VALUES ($1, $2, $3, $4)
RETURNING id, user_id, amount, status, note, requested_at, processed_by, processed_at
`

type CreateWithdrawalParams struct {
	UserID uuid.UUID `json:"user_id"`
	Amount int64     `json:"amount"`
	Note   string    `json:"note"`
	Source string    `json:"source"` // 'commission' | 'dividend'
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, createWithdrawal, arg.UserID, arg.Amount, arg.Note, arg.Source)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.RequestedAt,
		&i.ProcessedBy,
		&i.ProcessedAt,
	)
	return i, err
}

const listRevenueDistributions = `-- name: ListRevenueDistributions :many
SELECT id, period, total_revenue, pool_rate, investor_share_rate, investor_pool, dividend_id, created_by, created_at FROM revenue_distributions ORDER BY created_at DESC
`

func (q *Queries) ListRevenueDistributions(ctx context.Context) ([]RevenueDistribution, error) {
	rows, err := q.db.Query(ctx, listRevenueDistributions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueDistribution{}
	for rows.Next() {
		var i RevenueDistribution
		if err := rows.Scan(
			&i.ID,
			&i.Period,
			&i.TotalRevenue,
			&i.PoolRate,
			&i.InvestorShareRate,
			&i.InvestorPool,
			&i.DividendID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawals = `-- name: ListWithdrawals :many
SELECT w.id, w.user_id, w.amount, w.status, w.note, w.requested_at, w.processed_by, w.processed_at, w.source, u.full_name, u.email FROM withdrawals w
JOIN users u ON u.id = w.user_id
ORDER BY w.requested_at DESC
`

type ListWithdrawalsRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Amount      int64              `json:"amount"`
	Status      WithdrawalStatus   `json:"status"`
	Note        string             `json:"note"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	ProcessedBy uuid.NullUUID      `json:"processed_by"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	Source      string             `json:"source"`
	FullName    string             `json:"full_name"`
	Email       string             `json:"email"`
}

func (q *Queries) ListWithdrawals(ctx context.Context) ([]ListWithdrawalsRow, error) {
	rows, err := q.db.Query(ctx, listWithdrawals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWithdrawalsRow{}
	for rows.Next() {
		var i ListWithdrawalsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.Note,
			&i.RequestedAt,
			&i.ProcessedBy,
			&i.ProcessedAt,
			&i.Source,
			&i.FullName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalsByUser = `-- name: ListWithdrawalsByUser :many
SELECT id, user_id, amount, status, note, requested_at, processed_by, processed_at FROM withdrawals WHERE user_id = $1 AND source = 'commission' ORDER BY requested_at DESC
`

// Lịch sử rút VÍ HOA HỒNG (source='commission'). Rút cổ tức xem ListDividendWithdrawalsByUser.
func (q *Queries) ListWithdrawalsByUser(ctx context.Context, userID uuid.UUID) ([]Withdrawal, error) {
	rows, err := q.db.Query(ctx, listWithdrawalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Withdrawal{}
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.Note,
			&i.RequestedAt,
			&i.ProcessedBy,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWithdrawalStatus = `-- name: SetWithdrawalStatus :one
UPDATE withdrawals
SET status = $2, processed_by = $3, processed_at = now()
WHERE id = $1
RETURNING id, user_id, amount, status, note, requested_at, processed_by, processed_at
`

type SetWithdrawalStatusParams struct {
	ID          uuid.UUID        `json:"id"`
	Status      WithdrawalStatus `json:"status"`
	ProcessedBy uuid.NullUUID    `json:"processed_by"`
}

func (q *Queries) SetWithdrawalStatus(ctx context.Context, arg SetWithdrawalStatusParams) (Withdrawal, error) {
	row := q.db.QueryRow(ctx, setWithdrawalStatus, arg.ID, arg.Status, arg.ProcessedBy)
	var i Withdrawal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.RequestedAt,
		&i.ProcessedBy,
		&i.ProcessedAt,
	)
	return i, err
}

const sumRevenue = `-- name: SumRevenue :one
SELECT
    COALESCE(SUM(total_revenue), 0)::bigint AS total_revenue,
    COALESCE(SUM(investor_pool), 0)::bigint AS total_investor_pool
FROM revenue_distributions
`

type SumRevenueRow struct {
	TotalRevenue      int64 `json:"total_revenue"`
	TotalInvestorPool int64 `json:"total_investor_pool"`
}

func (q *Queries) SumRevenue(ctx context.Context) (SumRevenueRow, error) {
	row := q.db.QueryRow(ctx, sumRevenue)
	var i SumRevenueRow
	err := row.Scan(&i.TotalRevenue, &i.TotalInvestorPool)
	return i, err
}

const sumWithdrawalsByUser = `-- name: SumWithdrawalsByUser :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM withdrawals WHERE user_id = $1 AND source = 'commission' AND status <> 'rejected'
`

// tiền đã rút/đang chờ từ VÍ HOA HỒNG (source='commission', không tính rejected) — tính số dư khả dụng
func (q *Queries) SumWithdrawalsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumWithdrawalsByUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

// ----- VÍ CỔ TỨC (dividend) — số dư rút riêng, song song ví hoa hồng -----

const sumDividendPayoutsByUser = `-- name: SumDividendPayoutsByUser :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM dividend_payouts WHERE user_id = $1
`

// Tổng cổ tức được chia cho user (mọi đợt) — gốc của số dư cổ tức khả dụng.
func (q *Queries) SumDividendPayoutsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumDividendPayoutsByUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumDividendWithdrawalsByUser = `-- name: SumDividendWithdrawalsByUser :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM withdrawals WHERE user_id = $1 AND source = 'dividend' AND status <> 'rejected'
`

// Cổ tức đã rút/đang chờ (source='dividend', không tính rejected).
func (q *Queries) SumDividendWithdrawalsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumDividendWithdrawalsByUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listDividendWithdrawalsByUser = `-- name: ListDividendWithdrawalsByUser :many
SELECT id, user_id, amount, status, note, requested_at, processed_by, processed_at FROM withdrawals WHERE user_id = $1 AND source = 'dividend' ORDER BY requested_at DESC
`

// Lịch sử rút CỔ TỨC (source='dividend').
func (q *Queries) ListDividendWithdrawalsByUser(ctx context.Context, userID uuid.UUID) ([]Withdrawal, error) {
	rows, err := q.db.Query(ctx, listDividendWithdrawalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Withdrawal{}
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.Note,
			&i.RequestedAt,
			&i.ProcessedBy,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletBalances = `-- name: ListWalletBalances :many
SELECT
    u.id,
    u.email,
    u.full_name,
    (COALESCE(ic.earned, 0) + COALESCE(sc.earned, 0))::bigint                              AS earned,
    COALESCE(wd.withdrawn, 0)::bigint                                                      AS withdrawn,
    (COALESCE(ic.earned, 0) + COALESCE(sc.earned, 0) - COALESCE(wd.withdrawn, 0))::bigint  AS available,
    (COALESCE(ic.pending, 0) + COALESCE(sc.pending, 0))::bigint                            AS pending
FROM users u
JOIN (
    SELECT beneficiary_id FROM commissions       WHERE status <> 'rejected'
    UNION
    SELECT beneficiary_id FROM sales_commissions WHERE status <> 'rejected'
) b ON b.beneficiary_id = u.id
LEFT JOIN (
    SELECT beneficiary_id,
           SUM(net_amount)                                   AS earned,
           SUM(net_amount) FILTER (WHERE status = 'pending') AS pending
    FROM commissions WHERE status <> 'rejected' GROUP BY beneficiary_id
) ic ON ic.beneficiary_id = u.id
LEFT JOIN (
    SELECT beneficiary_id,
           SUM(net_amount)                                   AS earned,
           SUM(net_amount) FILTER (WHERE status = 'pending') AS pending
    FROM sales_commissions WHERE status <> 'rejected' GROUP BY beneficiary_id
) sc ON sc.beneficiary_id = u.id
LEFT JOIN (
    SELECT user_id, SUM(amount) AS withdrawn
    FROM withdrawals WHERE source = 'commission' AND status <> 'rejected' GROUP BY user_id
) wd ON wd.user_id = u.id
ORDER BY available DESC, u.full_name
`

type ListWalletBalancesRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	FullName  string    `json:"full_name"`
	Earned    int64     `json:"earned_vnd"`
	Withdrawn int64     `json:"withdrawn_vnd"`
	Available int64     `json:"available_vnd"`
	Pending   int64     `json:"pending_vnd"`
}

// ListWalletBalances — số dư ví hoa hồng của mọi tài khoản có phát sinh hoa hồng
// (đầu tư + bán hàng). Khớp công thức với WalletService.Balance().
func (q *Queries) ListWalletBalances(ctx context.Context) ([]ListWalletBalancesRow, error) {
	rows, err := q.db.Query(ctx, listWalletBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWalletBalancesRow
	for rows.Next() {
		var i ListWalletBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Earned,
			&i.Withdrawn,
			&i.Available,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
