// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dividend.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDividend = `-- name: DeleteDividend :exec
DELETE FROM dividends WHERE id = $1
`

func (q *Queries) DeleteDividend(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDividend, id)
	return err
}

const createDividend = `-- name: CreateDividend :one
INSERT INTO dividends (declared_by, period, total_amount, note)
VALUES ($1, $2, $3, $4)
RETURNING id, declared_by, declared_at, period, total_amount, note, created_at
`

type CreateDividendParams struct {
	DeclaredBy  uuid.UUID   `json:"declared_by"`
	Period      string      `json:"period"`
	TotalAmount int64       `json:"total_amount"`
	Note        pgtype.Text `json:"note"`
}

// INVARIANT 6: dividends exist ONLY because an admin created this row. No auto/cron path.
func (q *Queries) CreateDividend(ctx context.Context, arg CreateDividendParams) (Dividend, error) {
	row := q.db.QueryRow(ctx, createDividend,
		arg.DeclaredBy,
		arg.Period,
		arg.TotalAmount,
		arg.Note,
	)
	var i Dividend
	err := row.Scan(
		&i.ID,
		&i.DeclaredBy,
		&i.DeclaredAt,
		&i.Period,
		&i.TotalAmount,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createDividendPayout = `-- name: CreateDividendPayout :one
INSERT INTO dividend_payouts (dividend_id, user_id, shares, amount, equal_share, bonus, band, band_rate, invested_vnd)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (dividend_id, user_id) DO NOTHING
RETURNING id, dividend_id, user_id, shares, amount, paid_at, created_at, equal_share, bonus, band, band_rate, invested_vnd
`

type CreateDividendPayoutParams struct {
	DividendID  uuid.UUID `json:"dividend_id"`
	UserID      uuid.UUID `json:"user_id"`
	Shares      int64     `json:"shares"`
	Amount      int64     `json:"amount"`
	EqualShare  int64     `json:"equal_share"`
	Bonus       int64     `json:"bonus"`
	Band        string    `json:"band"`
	BandRate    float64   `json:"band_rate"`
	InvestedVnd int64     `json:"invested_vnd"`
}

func (q *Queries) CreateDividendPayout(ctx context.Context, arg CreateDividendPayoutParams) (DividendPayout, error) {
	row := q.db.QueryRow(ctx, createDividendPayout,
		arg.DividendID,
		arg.UserID,
		arg.Shares,
		arg.Amount,
		arg.EqualShare,
		arg.Bonus,
		arg.Band,
		arg.BandRate,
		arg.InvestedVnd,
	)
	var i DividendPayout
	err := row.Scan(
		&i.ID,
		&i.DividendID,
		&i.UserID,
		&i.Shares,
		&i.Amount,
		&i.PaidAt,
		&i.CreatedAt,
		&i.EqualShare,
		&i.Bonus,
		&i.Band,
		&i.BandRate,
		&i.InvestedVnd,
	)
	return i, err
}

const listDividends = `-- name: ListDividends :many
SELECT id, declared_by, declared_at, period, total_amount, note, created_at FROM dividends ORDER BY declared_at DESC
`

func (q *Queries) ListDividends(ctx context.Context) ([]Dividend, error) {
	rows, err := q.db.Query(ctx, listDividends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dividend{}
	for rows.Next() {
		var i Dividend
		if err := rows.Scan(
			&i.ID,
			&i.DeclaredBy,
			&i.DeclaredAt,
			&i.Period,
			&i.TotalAmount,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutsByDividend = `-- name: ListPayoutsByDividend :many
SELECT p.id, p.dividend_id, p.user_id, p.shares, p.amount, p.paid_at, p.created_at, p.equal_share, p.bonus, p.band, p.band_rate, p.invested_vnd, u.full_name, u.email FROM dividend_payouts p
JOIN users u ON u.id = p.user_id
WHERE p.dividend_id = $1
ORDER BY p.amount DESC
`

type ListPayoutsByDividendRow struct {
	ID          uuid.UUID          `json:"id"`
	DividendID  uuid.UUID          `json:"dividend_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Shares      int64              `json:"shares"`
	Amount      int64              `json:"amount"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EqualShare  int64              `json:"equal_share"`
	Bonus       int64              `json:"bonus"`
	Band        string             `json:"band"`
	BandRate    float64            `json:"band_rate"`
	InvestedVnd int64              `json:"invested_vnd"`
	FullName    string             `json:"full_name"`
	Email       string             `json:"email"`
}

func (q *Queries) ListPayoutsByDividend(ctx context.Context, dividendID uuid.UUID) ([]ListPayoutsByDividendRow, error) {
	rows, err := q.db.Query(ctx, listPayoutsByDividend, dividendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayoutsByDividendRow{}
	for rows.Next() {
		var i ListPayoutsByDividendRow
		if err := rows.Scan(
			&i.ID,
			&i.DividendID,
			&i.UserID,
			&i.Shares,
			&i.Amount,
			&i.PaidAt,
			&i.CreatedAt,
			&i.EqualShare,
			&i.Bonus,
			&i.Band,
			&i.BandRate,
			&i.InvestedVnd,
			&i.FullName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutsByUser = `-- name: ListPayoutsByUser :many
SELECT p.id, p.dividend_id, p.user_id, p.shares, p.amount, p.paid_at, p.created_at, d.period, d.note FROM dividend_payouts p
JOIN dividends d ON d.id = p.dividend_id
WHERE p.user_id = $1
ORDER BY p.created_at DESC
`

type ListPayoutsByUserRow struct {
	ID         uuid.UUID          `json:"id"`
	DividendID uuid.UUID          `json:"dividend_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Shares     int64              `json:"shares"`
	Amount     int64              `json:"amount"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Period     string             `json:"period"`
	Note       pgtype.Text        `json:"note"`
}

func (q *Queries) ListPayoutsByUser(ctx context.Context, userID uuid.UUID) ([]ListPayoutsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPayoutsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayoutsByUserRow{}
	for rows.Next() {
		var i ListPayoutsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.DividendID,
			&i.UserID,
			&i.Shares,
			&i.Amount,
			&i.PaidAt,
			&i.CreatedAt,
			&i.Period,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPayoutPaid = `-- name: MarkPayoutPaid :one
UPDATE dividend_payouts SET paid_at = now() WHERE id = $1 AND paid_at IS NULL
RETURNING id, dividend_id, user_id, shares, amount, paid_at, created_at
`

func (q *Queries) MarkPayoutPaid(ctx context.Context, id uuid.UUID) (DividendPayout, error) {
	row := q.db.QueryRow(ctx, markPayoutPaid, id)
	var i DividendPayout
	err := row.Scan(
		&i.ID,
		&i.DividendID,
		&i.UserID,
		&i.Shares,
		&i.Amount,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const sumDividendPaidToUser = `-- name: SumDividendPaidToUser :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM dividend_payouts WHERE user_id = $1 AND paid_at IS NOT NULL
`

// The ONLY "money received back" figure shown to investors: real dividends actually paid.
func (q *Queries) SumDividendPaidToUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumDividendPaidToUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
