// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createKYCRecord = `-- name: CreateKYCRecord :one
INSERT INTO kyc_records (user_id, cccd_number, cccd_image_url, cccd_back_url, selfie_url, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id, user_id, cccd_number, cccd_image_url, cccd_back_url, selfie_url, status, reject_reason, reviewed_by, reviewed_at, created_at
`

type CreateKYCRecordParams struct {
	UserID       uuid.UUID `json:"user_id"`
	CccdNumber   string    `json:"cccd_number"`
	CccdImageUrl string    `json:"cccd_image_url"`
	CccdBackUrl  string    `json:"cccd_back_url"`
	SelfieUrl    string    `json:"selfie_url"`
}

func (q *Queries) CreateKYCRecord(ctx context.Context, arg CreateKYCRecordParams) (KycRecord, error) {
	row := q.db.QueryRow(ctx, createKYCRecord,
		arg.UserID,
		arg.CccdNumber,
		arg.CccdImageUrl,
		arg.CccdBackUrl,
		arg.SelfieUrl,
	)
	var i KycRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CccdNumber,
		&i.CccdImageUrl,
		&i.CccdBackUrl,
		&i.SelfieUrl,
		&i.Status,
		&i.RejectReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getKYCByID = `-- name: GetKYCByID :one
SELECT id, user_id, cccd_number, cccd_image_url, cccd_back_url, selfie_url, status, reject_reason, reviewed_by, reviewed_at, created_at FROM kyc_records WHERE id = $1
`

func (q *Queries) GetKYCByID(ctx context.Context, id uuid.UUID) (KycRecord, error) {
	row := q.db.QueryRow(ctx, getKYCByID, id)
	var i KycRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CccdNumber,
		&i.CccdImageUrl,
		&i.CccdBackUrl,
		&i.SelfieUrl,
		&i.Status,
		&i.RejectReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestKYCByUser = `-- name: GetLatestKYCByUser :one
SELECT id, user_id, cccd_number, cccd_image_url, cccd_back_url, selfie_url, status, reject_reason, reviewed_by, reviewed_at, created_at FROM kyc_records WHERE user_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestKYCByUser(ctx context.Context, userID uuid.UUID) (KycRecord, error) {
	row := q.db.QueryRow(ctx, getLatestKYCByUser, userID)
	var i KycRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CccdNumber,
		&i.CccdImageUrl,
		&i.CccdBackUrl,
		&i.SelfieUrl,
		&i.Status,
		&i.RejectReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listConsentsByUser = `-- name: ListConsentsByUser :many
SELECT id, user_id, type, granted_at, ip, user_agent FROM consents WHERE user_id = $1 ORDER BY granted_at DESC
`

func (q *Queries) ListConsentsByUser(ctx context.Context, userID uuid.UUID) ([]Consent, error) {
	rows, err := q.db.Query(ctx, listConsentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Consent{}
	for rows.Next() {
		var i Consent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.GrantedAt,
			&i.Ip,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingKYC = `-- name: ListPendingKYC :many
SELECT id, user_id, cccd_number, cccd_image_url, cccd_back_url, selfie_url, status, reject_reason, reviewed_by, reviewed_at, created_at FROM kyc_records WHERE status = 'pending' ORDER BY created_at ASC
`

func (q *Queries) ListPendingKYC(ctx context.Context) ([]KycRecord, error) {
	rows, err := q.db.Query(ctx, listPendingKYC)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KycRecord{}
	for rows.Next() {
		var i KycRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CccdNumber,
			&i.CccdImageUrl,
			&i.CccdBackUrl,
			&i.SelfieUrl,
			&i.Status,
			&i.RejectReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordConsent = `-- name: RecordConsent :one
INSERT INTO consents (user_id, type, ip, user_agent)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, type, granted_at, ip, user_agent
`

type RecordConsentParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Type      string      `json:"type"`
	Ip        *netip.Addr `json:"ip"`
	UserAgent pgtype.Text `json:"user_agent"`
}

func (q *Queries) RecordConsent(ctx context.Context, arg RecordConsentParams) (Consent, error) {
	row := q.db.QueryRow(ctx, recordConsent,
		arg.UserID,
		arg.Type,
		arg.Ip,
		arg.UserAgent,
	)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.GrantedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const reviewKYC = `-- name: ReviewKYC :one
UPDATE kyc_records
SET status = $2, reject_reason = $3, reviewed_by = $4, reviewed_at = now()
WHERE id = $1
RETURNING id, user_id, cccd_number, cccd_image_url, cccd_back_url, selfie_url, status, reject_reason, reviewed_by, reviewed_at, created_at
`

type ReviewKYCParams struct {
	ID           uuid.UUID     `json:"id"`
	Status       KycStatus     `json:"status"`
	RejectReason pgtype.Text   `json:"reject_reason"`
	ReviewedBy   uuid.NullUUID `json:"reviewed_by"`
}

func (q *Queries) ReviewKYC(ctx context.Context, arg ReviewKYCParams) (KycRecord, error) {
	row := q.db.QueryRow(ctx, reviewKYC,
		arg.ID,
		arg.Status,
		arg.RejectReason,
		arg.ReviewedBy,
	)
	var i KycRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CccdNumber,
		&i.CccdImageUrl,
		&i.CccdBackUrl,
		&i.SelfieUrl,
		&i.Status,
		&i.RejectReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}
