// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investment.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContract = `-- name: CreateContract :one
INSERT INTO contracts (user_id, tier_id, status)
VALUES ($1, $2, 'draft')
RETURNING id, user_id, tier_id, pdf_url, signature_otp_ref, signed_at, status, created_at
`

type CreateContractParams struct {
	UserID uuid.UUID `json:"user_id"`
	TierID uuid.UUID `json:"tier_id"`
}

func (q *Queries) CreateContract(ctx context.Context, arg CreateContractParams) (Contract, error) {
	row := q.db.QueryRow(ctx, createContract, arg.UserID, arg.TierID)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierID,
		&i.PdfUrl,
		&i.SignatureOtpRef,
		&i.SignedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createInvestment = `-- name: CreateInvestment :one
INSERT INTO investments (code, user_id, contract_id, tier_id, amount_vnd, shares, status, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7)
RETURNING id, code, user_id, contract_id, tier_id, amount_vnd, shares, status, idempotency_key, reconciled_by, reconciled_at, approved_by, approved_at, rejected_by, rejected_at, reject_reason, created_at, updated_at
`

type CreateInvestmentParams struct {
	Code           string      `json:"code"`
	UserID         uuid.UUID   `json:"user_id"`
	ContractID     uuid.UUID   `json:"contract_id"`
	TierID         uuid.UUID   `json:"tier_id"`
	AmountVnd      int64       `json:"amount_vnd"`
	Shares         int64       `json:"shares"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, createInvestment,
		arg.Code,
		arg.UserID,
		arg.ContractID,
		arg.TierID,
		arg.AmountVnd,
		arg.Shares,
		arg.IdempotencyKey,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.ContractID,
		&i.TierID,
		&i.AmountVnd,
		&i.Shares,
		&i.Status,
		&i.IdempotencyKey,
		&i.ReconciledBy,
		&i.ReconciledAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (investment_id, bank, company_account, company_account_name, amount_vnd, transfer_note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, investment_id, bank, company_account, company_account_name, amount_vnd, transfer_note, declared_at, reconciled_at, reconciled_by, created_at
`

type CreatePaymentParams struct {
	InvestmentID       uuid.UUID `json:"investment_id"`
	Bank               string    `json:"bank"`
	CompanyAccount     string    `json:"company_account"`
	CompanyAccountName string    `json:"company_account_name"`
	AmountVnd          int64     `json:"amount_vnd"`
	TransferNote       string    `json:"transfer_note"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.InvestmentID,
		arg.Bank,
		arg.CompanyAccount,
		arg.CompanyAccountName,
		arg.AmountVnd,
		arg.TransferNote,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.Bank,
		&i.CompanyAccount,
		&i.CompanyAccountName,
		&i.AmountVnd,
		&i.TransferNote,
		&i.DeclaredAt,
		&i.ReconciledAt,
		&i.ReconciledBy,
		&i.CreatedAt,
	)
	return i, err
}

const declarePaymentTransferred = `-- name: DeclarePaymentTransferred :one
UPDATE payments SET declared_at = now() WHERE investment_id = $1 AND declared_at IS NULL
RETURNING id, investment_id, bank, company_account, company_account_name, amount_vnd, transfer_note, declared_at, reconciled_at, reconciled_by, created_at
`

func (q *Queries) DeclarePaymentTransferred(ctx context.Context, investmentID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, declarePaymentTransferred, investmentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.Bank,
		&i.CompanyAccount,
		&i.CompanyAccountName,
		&i.AmountVnd,
		&i.TransferNote,
		&i.DeclaredAt,
		&i.ReconciledAt,
		&i.ReconciledBy,
		&i.CreatedAt,
	)
	return i, err
}

const getContract = `-- name: GetContract :one
SELECT id, user_id, tier_id, pdf_url, signature_otp_ref, signed_at, status, created_at FROM contracts WHERE id = $1
`

func (q *Queries) GetContract(ctx context.Context, id uuid.UUID) (Contract, error) {
	row := q.db.QueryRow(ctx, getContract, id)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierID,
		&i.PdfUrl,
		&i.SignatureOtpRef,
		&i.SignedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getInvestment = `-- name: GetInvestment :one
SELECT id, code, user_id, contract_id, tier_id, amount_vnd, shares, status, idempotency_key, reconciled_by, reconciled_at, approved_by, approved_at, rejected_by, rejected_at, reject_reason, created_at, updated_at FROM investments WHERE id = $1
`

func (q *Queries) GetInvestment(ctx context.Context, id uuid.UUID) (Investment, error) {
	row := q.db.QueryRow(ctx, getInvestment, id)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.ContractID,
		&i.TierID,
		&i.AmountVnd,
		&i.Shares,
		&i.Status,
		&i.IdempotencyKey,
		&i.ReconciledBy,
		&i.ReconciledAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvestmentByIdempotencyKey = `-- name: GetInvestmentByIdempotencyKey :one
SELECT id, code, user_id, contract_id, tier_id, amount_vnd, shares, status, idempotency_key, reconciled_by, reconciled_at, approved_by, approved_at, rejected_by, rejected_at, reject_reason, created_at, updated_at FROM investments WHERE idempotency_key = $1
`

func (q *Queries) GetInvestmentByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Investment, error) {
	row := q.db.QueryRow(ctx, getInvestmentByIdempotencyKey, idempotencyKey)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.ContractID,
		&i.TierID,
		&i.AmountVnd,
		&i.Shares,
		&i.Status,
		&i.IdempotencyKey,
		&i.ReconciledBy,
		&i.ReconciledAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvestmentForUpdate = `-- name: GetInvestmentForUpdate :one
SELECT id, code, user_id, contract_id, tier_id, amount_vnd, shares, status, idempotency_key, reconciled_by, reconciled_at, approved_by, approved_at, rejected_by, rejected_at, reject_reason, created_at, updated_at FROM investments WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetInvestmentForUpdate(ctx context.Context, id uuid.UUID) (Investment, error) {
	row := q.db.QueryRow(ctx, getInvestmentForUpdate, id)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.ContractID,
		&i.TierID,
		&i.AmountVnd,
		&i.Shares,
		&i.Status,
		&i.IdempotencyKey,
		&i.ReconciledBy,
		&i.ReconciledAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByInvestment = `-- name: GetPaymentByInvestment :one
SELECT id, investment_id, bank, company_account, company_account_name, amount_vnd, transfer_note, declared_at, reconciled_at, reconciled_by, created_at FROM payments WHERE investment_id = $1
`

func (q *Queries) GetPaymentByInvestment(ctx context.Context, investmentID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByInvestment, investmentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.Bank,
		&i.CompanyAccount,
		&i.CompanyAccountName,
		&i.AmountVnd,
		&i.TransferNote,
		&i.DeclaredAt,
		&i.ReconciledAt,
		&i.ReconciledBy,
		&i.CreatedAt,
	)
	return i, err
}

const listInvestmentsByStatus = `-- name: ListInvestmentsByStatus :many
SELECT id, code, user_id, contract_id, tier_id, amount_vnd, shares, status, idempotency_key, reconciled_by, reconciled_at, approved_by, approved_at, rejected_by, rejected_at, reject_reason, created_at, updated_at FROM investments WHERE status = $1 ORDER BY created_at ASC
`

func (q *Queries) ListInvestmentsByStatus(ctx context.Context, status InvestmentStatus) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Investment{}
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.UserID,
			&i.ContractID,
			&i.TierID,
			&i.AmountVnd,
			&i.Shares,
			&i.Status,
			&i.IdempotencyKey,
			&i.ReconciledBy,
			&i.ReconciledAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentsByUser = `-- name: ListInvestmentsByUser :many
SELECT id, code, user_id, contract_id, tier_id, amount_vnd, shares, status, idempotency_key, reconciled_by, reconciled_at, approved_by, approved_at, rejected_by, rejected_at, reject_reason, created_at, updated_at FROM investments WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvestmentsByUser(ctx context.Context, userID uuid.UUID) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Investment{}
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.UserID,
			&i.ContractID,
			&i.TierID,
			&i.AmountVnd,
			&i.Shares,
			&i.Status,
			&i.IdempotencyKey,
			&i.ReconciledBy,
			&i.ReconciledAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvestmentApproved = `-- name: MarkInvestmentApproved :one
UPDATE investments
SET status = 'approved', approved_by = $2, approved_at = now(), updated_at = now()
WHERE id = $1 AND status = 'reconciled'
RETURNING id, code, user_id, contract_id, tier_id, amount_vnd, shares, status, idempotency_key, reconciled_by, reconciled_at, approved_by, approved_at, rejected_by, rejected_at, reject_reason, created_at, updated_at
`

type MarkInvestmentApprovedParams struct {
	ID         uuid.UUID     `json:"id"`
	ApprovedBy uuid.NullUUID `json:"approved_by"`
}

// INVARIANT 2: reconciled -> approved, stamping actor + timestamp.
func (q *Queries) MarkInvestmentApproved(ctx context.Context, arg MarkInvestmentApprovedParams) (Investment, error) {
	row := q.db.QueryRow(ctx, markInvestmentApproved, arg.ID, arg.ApprovedBy)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.ContractID,
		&i.TierID,
		&i.AmountVnd,
		&i.Shares,
		&i.Status,
		&i.IdempotencyKey,
		&i.ReconciledBy,
		&i.ReconciledAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markInvestmentReconciled = `-- name: MarkInvestmentReconciled :one
UPDATE investments
SET status = 'reconciled', reconciled_by = $2, reconciled_at = now(), updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, code, user_id, contract_id, tier_id, amount_vnd, shares, status, idempotency_key, reconciled_by, reconciled_at, approved_by, approved_at, rejected_by, rejected_at, reject_reason, created_at, updated_at
`

type MarkInvestmentReconciledParams struct {
	ID           uuid.UUID     `json:"id"`
	ReconciledBy uuid.NullUUID `json:"reconciled_by"`
}

// INVARIANT 2: pending -> reconciled, stamping actor + timestamp.
func (q *Queries) MarkInvestmentReconciled(ctx context.Context, arg MarkInvestmentReconciledParams) (Investment, error) {
	row := q.db.QueryRow(ctx, markInvestmentReconciled, arg.ID, arg.ReconciledBy)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.ContractID,
		&i.TierID,
		&i.AmountVnd,
		&i.Shares,
		&i.Status,
		&i.IdempotencyKey,
		&i.ReconciledBy,
		&i.ReconciledAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markInvestmentRejected = `-- name: MarkInvestmentRejected :one
UPDATE investments
SET status = 'rejected', rejected_by = $2, rejected_at = now(), reject_reason = $3, updated_at = now()
WHERE id = $1 AND status IN ('pending','reconciled')
RETURNING id, code, user_id, contract_id, tier_id, amount_vnd, shares, status, idempotency_key, reconciled_by, reconciled_at, approved_by, approved_at, rejected_by, rejected_at, reject_reason, created_at, updated_at
`

type MarkInvestmentRejectedParams struct {
	ID           uuid.UUID     `json:"id"`
	RejectedBy   uuid.NullUUID `json:"rejected_by"`
	RejectReason pgtype.Text   `json:"reject_reason"`
}

func (q *Queries) MarkInvestmentRejected(ctx context.Context, arg MarkInvestmentRejectedParams) (Investment, error) {
	row := q.db.QueryRow(ctx, markInvestmentRejected, arg.ID, arg.RejectedBy, arg.RejectReason)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.ContractID,
		&i.TierID,
		&i.AmountVnd,
		&i.Shares,
		&i.Status,
		&i.IdempotencyKey,
		&i.ReconciledBy,
		&i.ReconciledAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reconcilePayment = `-- name: ReconcilePayment :one
UPDATE payments
SET reconciled_at = now(), reconciled_by = $2
WHERE investment_id = $1 AND reconciled_at IS NULL
RETURNING id, investment_id, bank, company_account, company_account_name, amount_vnd, transfer_note, declared_at, reconciled_at, reconciled_by, created_at
`

type ReconcilePaymentParams struct {
	InvestmentID uuid.UUID     `json:"investment_id"`
	ReconciledBy uuid.NullUUID `json:"reconciled_by"`
}

// INVARIANT 7: funds reconciliation stamps actor + time before any share issuance.
func (q *Queries) ReconcilePayment(ctx context.Context, arg ReconcilePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, reconcilePayment, arg.InvestmentID, arg.ReconciledBy)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.Bank,
		&i.CompanyAccount,
		&i.CompanyAccountName,
		&i.AmountVnd,
		&i.TransferNote,
		&i.DeclaredAt,
		&i.ReconciledAt,
		&i.ReconciledBy,
		&i.CreatedAt,
	)
	return i, err
}

const signContract = `-- name: SignContract :one
UPDATE contracts
SET status = 'signed', signed_at = now(), signature_otp_ref = $2, pdf_url = $3
WHERE id = $1 AND status = 'draft'
RETURNING id, user_id, tier_id, pdf_url, signature_otp_ref, signed_at, status, created_at
`

type SignContractParams struct {
	ID              uuid.UUID   `json:"id"`
	SignatureOtpRef pgtype.Text `json:"signature_otp_ref"`
	PdfUrl          pgtype.Text `json:"pdf_url"`
}

func (q *Queries) SignContract(ctx context.Context, arg SignContractParams) (Contract, error) {
	row := q.db.QueryRow(ctx, signContract, arg.ID, arg.SignatureOtpRef, arg.PdfUrl)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierID,
		&i.PdfUrl,
		&i.SignatureOtpRef,
		&i.SignedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
