// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CommissionStatus string

const (
	CommissionStatusPending  CommissionStatus = "pending"
	CommissionStatusApproved CommissionStatus = "approved"
	CommissionStatusPaid     CommissionStatus = "paid"
	CommissionStatusRejected CommissionStatus = "rejected"
)

func (e *CommissionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommissionStatus(s)
	case string:
		*e = CommissionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CommissionStatus: %T", src)
	}
	return nil
}

type NullCommissionStatus struct {
	CommissionStatus CommissionStatus `json:"commission_status"`
	Valid            bool             `json:"valid"` // Valid is true if CommissionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommissionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CommissionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommissionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommissionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommissionStatus), nil
}

type ContractStatus string

const (
	ContractStatusDraft  ContractStatus = "draft"
	ContractStatusSigned ContractStatus = "signed"
	ContractStatusVoid   ContractStatus = "void"
)

func (e *ContractStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContractStatus(s)
	case string:
		*e = ContractStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContractStatus: %T", src)
	}
	return nil
}

type NullContractStatus struct {
	ContractStatus ContractStatus `json:"contract_status"`
	Valid          bool           `json:"valid"` // Valid is true if ContractStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContractStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContractStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContractStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContractStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContractStatus), nil
}

type InvestmentStatus string

const (
	InvestmentStatusPending    InvestmentStatus = "pending"
	InvestmentStatusReconciled InvestmentStatus = "reconciled"
	InvestmentStatusApproved   InvestmentStatus = "approved"
	InvestmentStatusRejected   InvestmentStatus = "rejected"
)

func (e *InvestmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvestmentStatus(s)
	case string:
		*e = InvestmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvestmentStatus: %T", src)
	}
	return nil
}

type NullInvestmentStatus struct {
	InvestmentStatus InvestmentStatus `json:"investment_status"`
	Valid            bool             `json:"valid"` // Valid is true if InvestmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvestmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvestmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvestmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvestmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvestmentStatus), nil
}

type KycStatus string

const (
	KycStatusUnverified KycStatus = "unverified"
	KycStatusPending    KycStatus = "pending"
	KycStatusApproved   KycStatus = "approved"
	KycStatusRejected   KycStatus = "rejected"
)

func (e *KycStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KycStatus(s)
	case string:
		*e = KycStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for KycStatus: %T", src)
	}
	return nil
}

type NullKycStatus struct {
	KycStatus KycStatus `json:"kyc_status"`
	Valid     bool      `json:"valid"` // Valid is true if KycStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKycStatus) Scan(value interface{}) error {
	if value == nil {
		ns.KycStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KycStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKycStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KycStatus), nil
}

type ReferralType string

const (
	ReferralTypeCustomer ReferralType = "customer"
	ReferralTypeInvestor ReferralType = "investor"
)

func (e *ReferralType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReferralType(s)
	case string:
		*e = ReferralType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReferralType: %T", src)
	}
	return nil
}

type NullReferralType struct {
	ReferralType ReferralType `json:"referral_type"`
	Valid        bool         `json:"valid"` // Valid is true if ReferralType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReferralType) Scan(value interface{}) error {
	if value == nil {
		ns.ReferralType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReferralType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReferralType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReferralType), nil
}

type UserRole string

const (
	UserRoleInvestor UserRole = "investor"
	UserRoleAdmin    UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type ReservationStatus string

const (
	ReservationStatusReserved  ReservationStatus = "reserved"
	ReservationStatusCancelled ReservationStatus = "cancelled"
)

func (e *ReservationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationStatus(s)
	case string:
		*e = ReservationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationStatus: %T", src)
	}
	return nil
}

type NullReservationStatus struct {
	ReservationStatus ReservationStatus `json:"reservation_status"`
	Valid             bool              `json:"valid"` // Valid is true if ReservationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationStatus), nil
}

type EarlyReservation struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	TierID       uuid.UUID          `json:"tier_id"`
	AmountVnd    int64              `json:"amount_vnd"`
	Shares       int64              `json:"shares"`
	OwnershipPct float64            `json:"ownership_pct"`
	Status       ReservationStatus  `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WithdrawalStatus string

const (
	WithdrawalStatusPending  WithdrawalStatus = "pending"
	WithdrawalStatusApproved WithdrawalStatus = "approved"
	WithdrawalStatusPaid     WithdrawalStatus = "paid"
	WithdrawalStatusRejected WithdrawalStatus = "rejected"
)

func (e *WithdrawalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WithdrawalStatus(s)
	case string:
		*e = WithdrawalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WithdrawalStatus: %T", src)
	}
	return nil
}

type NullWithdrawalStatus struct {
	WithdrawalStatus WithdrawalStatus `json:"withdrawal_status"`
	Valid            bool             `json:"valid"` // Valid is true if WithdrawalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWithdrawalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WithdrawalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WithdrawalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWithdrawalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WithdrawalStatus), nil
}

type AuditLog struct {
	ID        int64              `json:"id"`
	ActorID   uuid.NullUUID      `json:"actor_id"`
	Action    string             `json:"action"`
	Entity    string             `json:"entity"`
	EntityID  string             `json:"entity_id"`
	Before    []byte             `json:"before"`
	After     []byte             `json:"after"`
	Ip        *netip.Addr        `json:"ip"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Commission struct {
	ID            uuid.UUID          `json:"id"`
	ReferralID    uuid.UUID          `json:"referral_id"`
	InvestmentID  uuid.UUID          `json:"investment_id"`
	BaseAmount    int64              `json:"base_amount"`
	Rate          float64            `json:"rate"`
	Amount        int64              `json:"amount"`
	TaxPit        int64              `json:"tax_pit"`
	NetAmount     int64              `json:"net_amount"`
	Status        CommissionStatus   `json:"status"`
	ApprovedBy    uuid.NullUUID      `json:"approved_by"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Level         int16              `json:"level"`
	BeneficiaryID uuid.UUID          `json:"beneficiary_id"`
}

type Consent struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Type      string             `json:"type"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
	Ip        *netip.Addr        `json:"ip"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

type Contract struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	TierID          uuid.UUID          `json:"tier_id"`
	PdfUrl          pgtype.Text        `json:"pdf_url"`
	SignatureOtpRef pgtype.Text        `json:"signature_otp_ref"`
	SignedAt        pgtype.Timestamptz `json:"signed_at"`
	Status          ContractStatus     `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Dividend struct {
	ID          uuid.UUID          `json:"id"`
	DeclaredBy  uuid.UUID          `json:"declared_by"`
	DeclaredAt  pgtype.Timestamptz `json:"declared_at"`
	Period      string             `json:"period"`
	TotalAmount int64              `json:"total_amount"`
	Note        pgtype.Text        `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DividendPayout struct {
	ID          uuid.UUID          `json:"id"`
	DividendID  uuid.UUID          `json:"dividend_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Shares      int64              `json:"shares"`
	Amount      int64              `json:"amount"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	EqualShare  int64              `json:"equal_share"`
	Bonus       int64              `json:"bonus"`
	Band        string             `json:"band"`
	BandRate    float64            `json:"band_rate"`
	InvestedVnd int64              `json:"invested_vnd"`
}

type Investment struct {
	ID             uuid.UUID          `json:"id"`
	Code           string             `json:"code"`
	UserID         uuid.UUID          `json:"user_id"`
	ContractID     uuid.UUID          `json:"contract_id"`
	TierID         uuid.UUID          `json:"tier_id"`
	AmountVnd      int64              `json:"amount_vnd"`
	Shares         int64              `json:"shares"`
	Status         InvestmentStatus   `json:"status"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	ReconciledBy   uuid.NullUUID      `json:"reconciled_by"`
	ReconciledAt   pgtype.Timestamptz `json:"reconciled_at"`
	ApprovedBy     uuid.NullUUID      `json:"approved_by"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
	RejectedBy     uuid.NullUUID      `json:"rejected_by"`
	RejectedAt     pgtype.Timestamptz `json:"rejected_at"`
	RejectReason   pgtype.Text        `json:"reject_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type InvestmentTier struct {
	ID             uuid.UUID          `json:"id"`
	OfferingID     uuid.UUID          `json:"offering_id"`
	Name           string             `json:"name"`
	AmountVnd      int64              `json:"amount_vnd"`
	Shares         int64              `json:"shares"`
	OwnershipPct   float64            `json:"ownership_pct"`
	SortOrder      int32              `json:"sort_order"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CommissionRate float64            `json:"commission_rate"`
	IsSpecial      bool               `json:"is_special"`
}

type InvestorProfile struct {
	UserID            uuid.UUID          `json:"user_id"`
	DateOfBirth       string             `json:"date_of_birth"`
	Gender            string             `json:"gender"`
	Nationality       string             `json:"nationality"`
	CccdNumber        string             `json:"cccd_number"`
	CccdIssueDate     string             `json:"cccd_issue_date"`
	CccdIssuePlace    string             `json:"cccd_issue_place"`
	PermanentAddress  string             `json:"permanent_address"`
	ContactAddress    string             `json:"contact_address"`
	Occupation        string             `json:"occupation"`
	TaxCode           string             `json:"tax_code"`
	BankName          string             `json:"bank_name"`
	BankAccountNumber string             `json:"bank_account_number"`
	BankAccountName   string             `json:"bank_account_name"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type KycRecord struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	CccdNumber   string             `json:"cccd_number"`
	CccdImageUrl string             `json:"cccd_image_url"`
	CccdBackUrl  string             `json:"cccd_back_url"`
	SelfieUrl    string             `json:"selfie_url"`
	Status       KycStatus          `json:"status"`
	RejectReason pgtype.Text        `json:"reject_reason"`
	ReviewedBy   uuid.NullUUID      `json:"reviewed_by"`
	ReviewedAt   pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Offering struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	ValuationVnd  int64              `json:"valuation_vnd"`
	TotalShares   int64              `json:"total_shares"`
	SharesForSale int64              `json:"shares_for_sale"`
	SharesSold    int64              `json:"shares_sold"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID                 uuid.UUID          `json:"id"`
	InvestmentID       uuid.UUID          `json:"investment_id"`
	Bank               string             `json:"bank"`
	CompanyAccount     string             `json:"company_account"`
	CompanyAccountName string             `json:"company_account_name"`
	AmountVnd          int64              `json:"amount_vnd"`
	TransferNote       string             `json:"transfer_note"`
	DeclaredAt         pgtype.Timestamptz `json:"declared_at"`
	ReconciledAt       pgtype.Timestamptz `json:"reconciled_at"`
	ReconciledBy       uuid.NullUUID      `json:"reconciled_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Referral struct {
	RefereeID    uuid.UUID          `json:"referee_id"`
	ReferrerID   uuid.UUID          `json:"referrer_id"`
	ReferralType ReferralType       `json:"referral_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RevenueDistribution struct {
	ID                uuid.UUID          `json:"id"`
	Period            string             `json:"period"`
	TotalRevenue      int64              `json:"total_revenue"`
	PoolRate          float64            `json:"pool_rate"`
	InvestorShareRate float64            `json:"investor_share_rate"`
	InvestorPool      int64              `json:"investor_pool"`
	DividendID        uuid.NullUUID      `json:"dividend_id"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ShareLedger struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	InvestmentID uuid.NullUUID      `json:"investment_id"`
	SharesDelta  int64              `json:"shares_delta"`
	Reason       string             `json:"reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Shareholding struct {
	UserID       uuid.UUID          `json:"user_id"`
	Shares       int64              `json:"shares"`
	OwnershipPct float64            `json:"ownership_pct"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SiteSetting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy uuid.NullUUID      `json:"updated_by"`
}

type Upload struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Kind        string             `json:"kind"`
	ContentType string             `json:"content_type"`
	Path        string             `json:"path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	FullName     string             `json:"full_name"`
	Phone        string             `json:"phone"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	KycStatus    KycStatus          `json:"kyc_status"`
	KycMessage   string             `json:"kyc_message"`
	ReferralCode string             `json:"referral_code"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Withdrawal struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Amount      int64              `json:"amount"`
	Status      WithdrawalStatus   `json:"status"`
	Note        string             `json:"note"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	ProcessedBy uuid.NullUUID      `json:"processed_by"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}
