// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offering.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addSharesSold = `-- name: AddSharesSold :one
UPDATE offering
SET shares_sold = shares_sold + $2, updated_at = now()
WHERE id = $1
RETURNING id, name, valuation_vnd, total_shares, shares_for_sale, shares_sold, status, created_at, updated_at
`

type AddSharesSoldParams struct {
	ID         uuid.UUID `json:"id"`
	SharesSold int64     `json:"shares_sold"`
}

// INVARIANT 1 guard lives in the offering_sold_within_pool CHECK constraint; this fails the tx
// if it would push shares_sold past shares_for_sale.
func (q *Queries) AddSharesSold(ctx context.Context, arg AddSharesSoldParams) (Offering, error) {
	row := q.db.QueryRow(ctx, addSharesSold, arg.ID, arg.SharesSold)
	var i Offering
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ValuationVnd,
		&i.TotalShares,
		&i.SharesForSale,
		&i.SharesSold,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOfferings = `-- name: ListOfferings :many
SELECT id, name, valuation_vnd, total_shares, shares_for_sale, shares_sold, status, created_at, updated_at FROM offering ORDER BY created_at DESC
`

func (q *Queries) ListOfferings(ctx context.Context) ([]Offering, error) {
	rows, err := q.db.Query(ctx, listOfferings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offering
	for rows.Next() {
		var i Offering
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ValuationVnd,
			&i.TotalShares,
			&i.SharesForSale,
			&i.SharesSold,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeOpenOfferings = `-- name: CloseOpenOfferings :exec
UPDATE offering SET status = 'closed', updated_at = now() WHERE status = 'open'
`

func (q *Queries) CloseOpenOfferings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, closeOpenOfferings)
	return err
}

const createOffering = `-- name: CreateOffering :one
INSERT INTO offering (name, valuation_vnd, total_shares, shares_for_sale, shares_sold, status)
VALUES ($1, $2, $3, $4, 0, 'open')
RETURNING id, name, valuation_vnd, total_shares, shares_for_sale, shares_sold, status, created_at, updated_at
`

type CreateOfferingParams struct {
	Name          string `json:"name"`
	ValuationVnd  int64  `json:"valuation_vnd"`
	TotalShares   int64  `json:"total_shares"`
	SharesForSale int64  `json:"shares_for_sale"`
}

func (q *Queries) CreateOffering(ctx context.Context, arg CreateOfferingParams) (Offering, error) {
	row := q.db.QueryRow(ctx, createOffering,
		arg.Name,
		arg.ValuationVnd,
		arg.TotalShares,
		arg.SharesForSale,
	)
	var i Offering
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ValuationVnd,
		&i.TotalShares,
		&i.SharesForSale,
		&i.SharesSold,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveOffering = `-- name: GetActiveOffering :one
SELECT id, name, valuation_vnd, total_shares, shares_for_sale, shares_sold, status, created_at, updated_at FROM offering WHERE status = 'open' ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) GetActiveOffering(ctx context.Context) (Offering, error) {
	row := q.db.QueryRow(ctx, getActiveOffering)
	var i Offering
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ValuationVnd,
		&i.TotalShares,
		&i.SharesForSale,
		&i.SharesSold,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfferingForUpdate = `-- name: GetOfferingForUpdate :one
SELECT id, name, valuation_vnd, total_shares, shares_for_sale, shares_sold, status, created_at, updated_at FROM offering WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetOfferingForUpdate(ctx context.Context, id uuid.UUID) (Offering, error) {
	row := q.db.QueryRow(ctx, getOfferingForUpdate, id)
	var i Offering
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ValuationVnd,
		&i.TotalShares,
		&i.SharesForSale,
		&i.SharesSold,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTier = `-- name: CreateTier :one
INSERT INTO investment_tiers (offering_id, name, amount_vnd, shares, ownership_pct, sort_order, active, is_special)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, offering_id, name, amount_vnd, shares, ownership_pct, sort_order, active, created_at, commission_rate, is_special
`

type CreateTierParams struct {
	OfferingID   uuid.UUID `json:"offering_id"`
	Name         string    `json:"name"`
	AmountVnd    int64     `json:"amount_vnd"`
	Shares       int64     `json:"shares"`
	OwnershipPct float64   `json:"ownership_pct"`
	SortOrder    int32     `json:"sort_order"`
	Active       bool      `json:"active"`
	IsSpecial    bool      `json:"is_special"`
}

func (q *Queries) CreateTier(ctx context.Context, arg CreateTierParams) (InvestmentTier, error) {
	row := q.db.QueryRow(ctx, createTier,
		arg.OfferingID,
		arg.Name,
		arg.AmountVnd,
		arg.Shares,
		arg.OwnershipPct,
		arg.SortOrder,
		arg.Active,
		arg.IsSpecial,
	)
	var i InvestmentTier
	err := row.Scan(
		&i.ID,
		&i.OfferingID,
		&i.Name,
		&i.AmountVnd,
		&i.Shares,
		&i.OwnershipPct,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.CommissionRate,
		&i.IsSpecial,
	)
	return i, err
}

const getTier = `-- name: GetTier :one
SELECT id, offering_id, name, amount_vnd, shares, ownership_pct, sort_order, active, created_at, commission_rate, is_special FROM investment_tiers WHERE id = $1
`

func (q *Queries) GetTier(ctx context.Context, id uuid.UUID) (InvestmentTier, error) {
	row := q.db.QueryRow(ctx, getTier, id)
	var i InvestmentTier
	err := row.Scan(
		&i.ID,
		&i.OfferingID,
		&i.Name,
		&i.AmountVnd,
		&i.Shares,
		&i.OwnershipPct,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.CommissionRate,
		&i.IsSpecial,
	)
	return i, err
}

const listAllTiers = `-- name: ListAllTiers :many
SELECT id, offering_id, name, amount_vnd, shares, ownership_pct, sort_order, active, created_at, commission_rate, is_special FROM investment_tiers
WHERE offering_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListAllTiers(ctx context.Context, offeringID uuid.UUID) ([]InvestmentTier, error) {
	rows, err := q.db.Query(ctx, listAllTiers, offeringID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvestmentTier{}
	for rows.Next() {
		var i InvestmentTier
		if err := rows.Scan(
			&i.ID,
			&i.OfferingID,
			&i.Name,
			&i.AmountVnd,
			&i.Shares,
			&i.OwnershipPct,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.CommissionRate,
			&i.IsSpecial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTiers = `-- name: ListTiers :many
SELECT id, offering_id, name, amount_vnd, shares, ownership_pct, sort_order, active, created_at, commission_rate, is_special FROM investment_tiers
WHERE offering_id = $1 AND active = true AND is_special = false
ORDER BY sort_order ASC
`

func (q *Queries) ListTiers(ctx context.Context, offeringID uuid.UUID) ([]InvestmentTier, error) {
	rows, err := q.db.Query(ctx, listTiers, offeringID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvestmentTier{}
	for rows.Next() {
		var i InvestmentTier
		if err := rows.Scan(
			&i.ID,
			&i.OfferingID,
			&i.Name,
			&i.AmountVnd,
			&i.Shares,
			&i.OwnershipPct,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.CommissionRate,
			&i.IsSpecial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTiersForUser = `-- name: ListTiersForUser :many
SELECT id, offering_id, name, amount_vnd, shares, ownership_pct, sort_order, active, created_at, commission_rate, is_special FROM investment_tiers
WHERE offering_id = $1 AND active = true
  AND (is_special = false OR $2::boolean = true)
ORDER BY sort_order ASC
`

type ListTiersForUserParams struct {
	OfferingID     uuid.UUID `json:"offering_id"`
	IncludeSpecial bool      `json:"include_special"`
}

func (q *Queries) ListTiersForUser(ctx context.Context, arg ListTiersForUserParams) ([]InvestmentTier, error) {
	rows, err := q.db.Query(ctx, listTiersForUser, arg.OfferingID, arg.IncludeSpecial)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvestmentTier{}
	for rows.Next() {
		var i InvestmentTier
		if err := rows.Scan(
			&i.ID,
			&i.OfferingID,
			&i.Name,
			&i.AmountVnd,
			&i.Shares,
			&i.OwnershipPct,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.CommissionRate,
			&i.IsSpecial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTierActive = `-- name: SetTierActive :one
UPDATE investment_tiers SET active = $2 WHERE id = $1 RETURNING id, offering_id, name, amount_vnd, shares, ownership_pct, sort_order, active, created_at, commission_rate, is_special
`

type SetTierActiveParams struct {
	ID     uuid.UUID `json:"id"`
	Active bool      `json:"active"`
}

func (q *Queries) SetTierActive(ctx context.Context, arg SetTierActiveParams) (InvestmentTier, error) {
	row := q.db.QueryRow(ctx, setTierActive, arg.ID, arg.Active)
	var i InvestmentTier
	err := row.Scan(
		&i.ID,
		&i.OfferingID,
		&i.Name,
		&i.AmountVnd,
		&i.Shares,
		&i.OwnershipPct,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.CommissionRate,
		&i.IsSpecial,
	)
	return i, err
}

const tierInUse = `-- name: TierInUse :one
SELECT EXISTS (
    SELECT 1 FROM contracts   WHERE tier_id = $1
    UNION ALL
    SELECT 1 FROM investments WHERE tier_id = $1
) AS in_use
`

func (q *Queries) TierInUse(ctx context.Context, tierID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, tierInUse, tierID)
	var in_use bool
	err := row.Scan(&in_use)
	return in_use, err
}

const deleteTier = `-- name: DeleteTier :exec
DELETE FROM investment_tiers WHERE id = $1
`

func (q *Queries) DeleteTier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTier, id)
	return err
}

const updateTier = `-- name: UpdateTier :one
UPDATE investment_tiers
SET name = $2, amount_vnd = $3, shares = $4, ownership_pct = $5, sort_order = $6, active = $7, is_special = $8
WHERE id = $1
RETURNING id, offering_id, name, amount_vnd, shares, ownership_pct, sort_order, active, created_at, commission_rate, is_special
`

type UpdateTierParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	AmountVnd    int64     `json:"amount_vnd"`
	Shares       int64     `json:"shares"`
	OwnershipPct float64   `json:"ownership_pct"`
	SortOrder    int32     `json:"sort_order"`
	Active       bool      `json:"active"`
	IsSpecial    bool      `json:"is_special"`
}

func (q *Queries) UpdateTier(ctx context.Context, arg UpdateTierParams) (InvestmentTier, error) {
	row := q.db.QueryRow(ctx, updateTier,
		arg.ID,
		arg.Name,
		arg.AmountVnd,
		arg.Shares,
		arg.OwnershipPct,
		arg.SortOrder,
		arg.Active,
		arg.IsSpecial,
	)
	var i InvestmentTier
	err := row.Scan(
		&i.ID,
		&i.OfferingID,
		&i.Name,
		&i.AmountVnd,
		&i.Shares,
		&i.OwnershipPct,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.CommissionRate,
		&i.IsSpecial,
	)
	return i, err
}

const sumShareholdings = `-- name: SumShareholdings :one
SELECT COALESCE(SUM(shares), 0)::bigint AS total FROM shareholdings
`

func (q *Queries) SumShareholdings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumShareholdings)
	var total int64
	err := row.Scan(&total)
	return total, err
}
