// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getProfile = `-- name: GetProfile :one
SELECT user_id, date_of_birth, gender, nationality, cccd_number, cccd_issue_date, cccd_issue_place, permanent_address, contact_address, occupation, tax_code, bank_name, bank_account_number, bank_account_name, updated_at FROM investor_profiles WHERE user_id = $1
`

func (q *Queries) GetProfile(ctx context.Context, userID uuid.UUID) (InvestorProfile, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i InvestorProfile
	err := row.Scan(
		&i.UserID,
		&i.DateOfBirth,
		&i.Gender,
		&i.Nationality,
		&i.CccdNumber,
		&i.CccdIssueDate,
		&i.CccdIssuePlace,
		&i.PermanentAddress,
		&i.ContactAddress,
		&i.Occupation,
		&i.TaxCode,
		&i.BankName,
		&i.BankAccountNumber,
		&i.BankAccountName,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO investor_profiles (
    user_id, date_of_birth, gender, nationality, cccd_number, cccd_issue_date,
    cccd_issue_place, permanent_address, contact_address, occupation, tax_code,
    bank_name, bank_account_number, bank_account_name, updated_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14, now())
ON CONFLICT (user_id) DO UPDATE SET
    date_of_birth = EXCLUDED.date_of_birth,
    gender = EXCLUDED.gender,
    nationality = EXCLUDED.nationality,
    cccd_number = EXCLUDED.cccd_number,
    cccd_issue_date = EXCLUDED.cccd_issue_date,
    cccd_issue_place = EXCLUDED.cccd_issue_place,
    permanent_address = EXCLUDED.permanent_address,
    contact_address = EXCLUDED.contact_address,
    occupation = EXCLUDED.occupation,
    tax_code = EXCLUDED.tax_code,
    bank_name = EXCLUDED.bank_name,
    bank_account_number = EXCLUDED.bank_account_number,
    bank_account_name = EXCLUDED.bank_account_name,
    updated_at = now()
RETURNING user_id, date_of_birth, gender, nationality, cccd_number, cccd_issue_date, cccd_issue_place, permanent_address, contact_address, occupation, tax_code, bank_name, bank_account_number, bank_account_name, updated_at
`

type UpsertProfileParams struct {
	UserID            uuid.UUID `json:"user_id"`
	DateOfBirth       string    `json:"date_of_birth"`
	Gender            string    `json:"gender"`
	Nationality       string    `json:"nationality"`
	CccdNumber        string    `json:"cccd_number"`
	CccdIssueDate     string    `json:"cccd_issue_date"`
	CccdIssuePlace    string    `json:"cccd_issue_place"`
	PermanentAddress  string    `json:"permanent_address"`
	ContactAddress    string    `json:"contact_address"`
	Occupation        string    `json:"occupation"`
	TaxCode           string    `json:"tax_code"`
	BankName          string    `json:"bank_name"`
	BankAccountNumber string    `json:"bank_account_number"`
	BankAccountName   string    `json:"bank_account_name"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (InvestorProfile, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.UserID,
		arg.DateOfBirth,
		arg.Gender,
		arg.Nationality,
		arg.CccdNumber,
		arg.CccdIssueDate,
		arg.CccdIssuePlace,
		arg.PermanentAddress,
		arg.ContactAddress,
		arg.Occupation,
		arg.TaxCode,
		arg.BankName,
		arg.BankAccountNumber,
		arg.BankAccountName,
	)
	var i InvestorProfile
	err := row.Scan(
		&i.UserID,
		&i.DateOfBirth,
		&i.Gender,
		&i.Nationality,
		&i.CccdNumber,
		&i.CccdIssueDate,
		&i.CccdIssuePlace,
		&i.PermanentAddress,
		&i.ContactAddress,
		&i.Occupation,
		&i.TaxCode,
		&i.BankName,
		&i.BankAccountNumber,
		&i.BankAccountName,
		&i.UpdatedAt,
	)
	return i, err
}
