// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// INVARIANT 1 guard lives in the offering_sold_within_pool CHECK constraint; this fails the tx
	// if it would push shares_sold past shares_for_sale.
	AddSharesSold(ctx context.Context, arg AddSharesSoldParams) (Offering, error)
	AdminStats(ctx context.Context) (AdminStatsRow, error)
	CreateOffering(ctx context.Context, arg CreateOfferingParams) (Offering, error)
	CloseOpenOfferings(ctx context.Context) error
	ListOfferings(ctx context.Context) ([]Offering, error)
	CreateTier(ctx context.Context, arg CreateTierParams) (InvestmentTier, error)
	DeleteTier(ctx context.Context, id uuid.UUID) error
	TierInUse(ctx context.Context, tierID uuid.UUID) (bool, error)
	ListAllTiers(ctx context.Context, offeringID uuid.UUID) ([]InvestmentTier, error)
	ListTiersForUser(ctx context.Context, arg ListTiersForUserParams) ([]InvestmentTier, error)
	SetTierActive(ctx context.Context, arg SetTierActiveParams) (InvestmentTier, error)
	UpdateTier(ctx context.Context, arg UpdateTierParams) (InvestmentTier, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	IsReferredByAdmin(ctx context.Context, refereeID uuid.UUID) (bool, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (EarlyReservation, error)
	GetReservationByUserTier(ctx context.Context, arg GetReservationByUserTierParams) (EarlyReservation, error)
	ListReservationsByUser(ctx context.Context, userID uuid.UUID) ([]ListReservationsByUserRow, error)
	ListAllReservations(ctx context.Context) ([]ListAllReservationsRow, error)
	SetReservationStatus(ctx context.Context, arg SetReservationStatusParams) (EarlyReservation, error)
	ApproveCommission(ctx context.Context, arg ApproveCommissionParams) (Commission, error)
	CapTable(ctx context.Context) ([]CapTableRow, error)
	CountUsersByRole(ctx context.Context, role UserRole) (int64, error)
	// INVARIANT 5: only on approved investments. Multi-level (F1/F2/F3): one row per (investment, level),
	// each crediting beneficiary_id (the upline earner at that level). referral_id stays the chain
	// ORIGIN (the investor's referee_id) so type lookups still join on referrals.referral_type.
	CreateCommission(ctx context.Context, arg CreateCommissionParams) (Commission, error)
	CreateContract(ctx context.Context, arg CreateContractParams) (Contract, error)
	// INVARIANT 6: dividends exist ONLY because an admin created this row. No auto/cron path.
	CreateDividend(ctx context.Context, arg CreateDividendParams) (Dividend, error)
	CreateDividendPayout(ctx context.Context, arg CreateDividendPayoutParams) (DividendPayout, error)
	CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error)
	CreateKYCRecord(ctx context.Context, arg CreateKYCRecordParams) (KycRecord, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	// 1-LEVEL ONLY: stores the direct referrer for a referee. PK on referee_id => at most one referrer.
	CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error)
	CreateRevenueDistribution(ctx context.Context, arg CreateRevenueDistributionParams) (RevenueDistribution, error)
	CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error)
	DeclarePaymentTransferred(ctx context.Context, investmentID uuid.UUID) (Payment, error)
	// Account deletion (admin "safe delete"): footprint check + ordered cleanup.
	UserDeletionStats(ctx context.Context, userID uuid.UUID) (UserDeletionStatsRow, error)
	ListUploadPathsByUser(ctx context.Context, userID uuid.UUID) ([]string, error)
	DeleteInvestmentsByUser(ctx context.Context, userID uuid.UUID) error
	DeleteOutgoingReferrals(ctx context.Context, referrerID uuid.UUID) error
	DeleteContractsByUser(ctx context.Context, userID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	// Account deletion (admin "hard delete"): wipe financial footprint + return shares to the pool.
	DisableShareLedgerImmutability(ctx context.Context) error
	EnableShareLedgerImmutability(ctx context.Context) error
	DeleteShareLedgerByUser(ctx context.Context, userID uuid.UUID) error
	DeleteShareholdingByUser(ctx context.Context, userID uuid.UUID) error
	DeleteDividendPayoutsByUser(ctx context.Context, userID uuid.UUID) error
	DeleteWithdrawalsByUser(ctx context.Context, userID uuid.UUID) error
	DeleteCommissionsForInvestmentsByUser(ctx context.Context, userID uuid.UUID) error
	DeleteCommissionsEarnedByReferrer(ctx context.Context, referrerID uuid.UUID) error
	RecomputeSharesSold(ctx context.Context) error
	EnsureAdmin(ctx context.Context, arg EnsureAdminParams) (User, error)
	GetActiveOffering(ctx context.Context) (Offering, error)
	GetContract(ctx context.Context, id uuid.UUID) (Contract, error)
	GetInvestment(ctx context.Context, id uuid.UUID) (Investment, error)
	GetInvestmentByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Investment, error)
	GetInvestmentForUpdate(ctx context.Context, id uuid.UUID) (Investment, error)
	GetKYCByID(ctx context.Context, id uuid.UUID) (KycRecord, error)
	GetLatestKYCByUser(ctx context.Context, userID uuid.UUID) (KycRecord, error)
	GetOfferingForUpdate(ctx context.Context, id uuid.UUID) (Offering, error)
	GetPaymentByInvestment(ctx context.Context, investmentID uuid.UUID) (Payment, error)
	GetProfile(ctx context.Context, userID uuid.UUID) (InvestorProfile, error)
	GetReferralByReferee(ctx context.Context, refereeID uuid.UUID) (Referral, error)
	GetShareholding(ctx context.Context, userID uuid.UUID) (Shareholding, error)
	GetTier(ctx context.Context, id uuid.UUID) (InvestmentTier, error)
	GetUpload(ctx context.Context, id uuid.UUID) (Upload, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByReferralCode(ctx context.Context, referralCode string) (User, error)
	// INVARIANT 8: called inside the same tx as the mutation it records. Table is append-only.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertShareLedger(ctx context.Context, arg InsertShareLedgerParams) (ShareLedger, error)
	// Active shareholders with their TRUE invested capital (sum of approved investments) — the basis
	// for the tiered bonus banding. invested_vnd uses amount_vnd, not shares×price, so a 50tr package
	// bands exactly on the 50tr boundary rather than 49.5tr.
	ListActiveAccounts(ctx context.Context) ([]ListActiveAccountsRow, error)
	ListAllShareholdings(ctx context.Context) ([]Shareholding, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	// All commissions EARNED by a user across every level (F1/F2/F3) — keyed by beneficiary_id.
	ListCommissionsByReferrer(ctx context.Context, beneficiaryID uuid.UUID) ([]Commission, error)
	ListConsentsByUser(ctx context.Context, userID uuid.UUID) ([]Consent, error)
	ListDividends(ctx context.Context) ([]Dividend, error)
	// Số dư ví hoa hồng của mọi tài khoản có hoa hồng (đầu tư + bán hàng) — cho admin rút dùm.
	ListWalletBalances(ctx context.Context) ([]ListWalletBalancesRow, error)
	// Manual delete of a distribution round (admin): revenue_distributions + dividend (+payouts cascade).
	GetRevenueDistribution(ctx context.Context, id uuid.UUID) (RevenueDistribution, error)
	DeleteRevenueDistribution(ctx context.Context, id uuid.UUID) error
	DeleteRevenueDistributionsByDividend(ctx context.Context, dividendID uuid.NullUUID) error
	DeleteDividend(ctx context.Context, id uuid.UUID) error
	ListInvestmentsByStatus(ctx context.Context, status InvestmentStatus) ([]Investment, error)
	ListInvestmentsByUser(ctx context.Context, userID uuid.UUID) ([]Investment, error)
	ListPayoutsByDividend(ctx context.Context, dividendID uuid.UUID) ([]ListPayoutsByDividendRow, error)
	ListPayoutsByUser(ctx context.Context, userID uuid.UUID) ([]ListPayoutsByUserRow, error)
	ListPendingKYC(ctx context.Context) ([]KycRecord, error)
	ListReferralsByReferrer(ctx context.Context, referrerID uuid.UUID) ([]Referral, error)
	ListRevenueDistributions(ctx context.Context) ([]RevenueDistribution, error)
	ListSettings(ctx context.Context) ([]ListSettingsRow, error)
	ListTiers(ctx context.Context, offeringID uuid.UUID) ([]InvestmentTier, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListWithdrawals(ctx context.Context) ([]ListWithdrawalsRow, error)
	ListWithdrawalsByUser(ctx context.Context, userID uuid.UUID) ([]Withdrawal, error)
	// INVARIANT 2: reconciled -> approved, stamping actor + timestamp.
	MarkInvestmentApproved(ctx context.Context, arg MarkInvestmentApprovedParams) (Investment, error)
	// INVARIANT 2: pending -> reconciled, stamping actor + timestamp.
	MarkInvestmentReconciled(ctx context.Context, arg MarkInvestmentReconciledParams) (Investment, error)
	MarkInvestmentRejected(ctx context.Context, arg MarkInvestmentRejectedParams) (Investment, error)
	MarkPayoutPaid(ctx context.Context, id uuid.UUID) (DividendPayout, error)
	PayCommission(ctx context.Context, id uuid.UUID) (Commission, error)
	// INVARIANT 7: funds reconciliation stamps actor + time before any share issuance.
	ReconcilePayment(ctx context.Context, arg ReconcilePaymentParams) (Payment, error)
	RecordConsent(ctx context.Context, arg RecordConsentParams) (Consent, error)
	ReviewKYC(ctx context.Context, arg ReviewKYCParams) (KycRecord, error)
	SetShareholdingPct(ctx context.Context, arg SetShareholdingPctParams) error
	SetUserKYCStatus(ctx context.Context, arg SetUserKYCStatusParams) error
	SetUserKYCResult(ctx context.Context, arg SetUserKYCResultParams) error
	SetWithdrawalStatus(ctx context.Context, arg SetWithdrawalStatusParams) (Withdrawal, error)
	SignContract(ctx context.Context, arg SignContractParams) (Contract, error)
	// Tổng hoa hồng (net) khả dụng của 1 người (mọi cấp F1/F2/F3, mọi trạng thái trừ rejected) — số dư ví.
	// Cộng vào ví ngay; điểm kiểm soát là khâu DUYỆT RÚT TIỀN của admin.
	SumCommissionEarnedByReferrer(ctx context.Context, beneficiaryID uuid.UUID) (int64, error)
	// Hoa hồng (net) CHƯA DUYỆT của 1 người — phần đang chờ admin duyệt (đã gộp trong số dư khả dụng).
	SumPendingCommissionByBeneficiary(ctx context.Context, beneficiaryID uuid.UUID) (int64, error)
	SumCommissionsByType(ctx context.Context, referralType ReferralType) (SumCommissionsByTypeRow, error)
	// The ONLY "money received back" figure shown to investors: real dividends actually paid.
	SumDividendPaidToUser(ctx context.Context, userID uuid.UUID) (int64, error)
	// INVARIANT 4: reconcile shareholdings against the append-only ledger at any time.
	SumLedgerByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	SumRevenue(ctx context.Context) (SumRevenueRow, error)
	SumShareholdings(ctx context.Context) (int64, error)
	// tiền đã rút hoặc đang chờ (không tính rejected) — để tính số dư khả dụng
	SumWithdrawalsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	UpsertProfile(ctx context.Context, arg UpsertProfileParams) (InvestorProfile, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (SiteSetting, error)
	// Keeps the read model in lock-step with the ledger inside the issuing tx.
	UpsertShareholding(ctx context.Context, arg UpsertShareholdingParams) (Shareholding, error)
}

var _ Querier = (*Queries)(nil)
