// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referral.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const approveCommission = `-- name: ApproveCommission :one
UPDATE commissions SET status = 'approved', approved_by = $2 WHERE id = $1 AND status = 'pending'
RETURNING id, referral_id, investment_id, base_amount, rate, amount, tax_pit, net_amount, status, approved_by, paid_at, created_at, level, beneficiary_id
`

type ApproveCommissionParams struct {
	ID         uuid.UUID     `json:"id"`
	ApprovedBy uuid.NullUUID `json:"approved_by"`
}

func (q *Queries) ApproveCommission(ctx context.Context, arg ApproveCommissionParams) (Commission, error) {
	row := q.db.QueryRow(ctx, approveCommission, arg.ID, arg.ApprovedBy)
	var i Commission
	err := row.Scan(
		&i.ID,
		&i.ReferralID,
		&i.InvestmentID,
		&i.BaseAmount,
		&i.Rate,
		&i.Amount,
		&i.TaxPit,
		&i.NetAmount,
		&i.Status,
		&i.ApprovedBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.Level,
		&i.BeneficiaryID,
	)
	return i, err
}

const createCommission = `-- name: CreateCommission :one
INSERT INTO commissions (referral_id, investment_id, base_amount, rate, amount, tax_pit, net_amount, status, level, beneficiary_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending', $8, $9)
ON CONFLICT (investment_id, level) DO NOTHING
RETURNING id, referral_id, investment_id, base_amount, rate, amount, tax_pit, net_amount, status, approved_by, paid_at, created_at, level, beneficiary_id
`

type CreateCommissionParams struct {
	ReferralID    uuid.UUID `json:"referral_id"`
	InvestmentID  uuid.UUID `json:"investment_id"`
	BaseAmount    int64     `json:"base_amount"`
	Rate          float64   `json:"rate"`
	Amount        int64     `json:"amount"`
	TaxPit        int64     `json:"tax_pit"`
	NetAmount     int64     `json:"net_amount"`
	Level         int16     `json:"level"`
	BeneficiaryID uuid.UUID `json:"beneficiary_id"`
}

// INVARIANT 5: only on approved investments. Multi-level (F1/F2/F3): one row per (investment, level),
// each crediting beneficiary_id (the upline earner at that level). referral_id stays the chain
// ORIGIN (the investor's referee_id) so type lookups still join on referrals.referral_type.
func (q *Queries) CreateCommission(ctx context.Context, arg CreateCommissionParams) (Commission, error) {
	row := q.db.QueryRow(ctx, createCommission,
		arg.ReferralID,
		arg.InvestmentID,
		arg.BaseAmount,
		arg.Rate,
		arg.Amount,
		arg.TaxPit,
		arg.NetAmount,
		arg.Level,
		arg.BeneficiaryID,
	)
	var i Commission
	err := row.Scan(
		&i.ID,
		&i.ReferralID,
		&i.InvestmentID,
		&i.BaseAmount,
		&i.Rate,
		&i.Amount,
		&i.TaxPit,
		&i.NetAmount,
		&i.Status,
		&i.ApprovedBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.Level,
		&i.BeneficiaryID,
	)
	return i, err
}

const createReferral = `-- name: CreateReferral :one
INSERT INTO referrals (referee_id, referrer_id, referral_type)
VALUES ($1, $2, $3)
ON CONFLICT (referee_id) DO NOTHING
RETURNING referee_id, referrer_id, referral_type, created_at
`

type CreateReferralParams struct {
	RefereeID    uuid.UUID    `json:"referee_id"`
	ReferrerID   uuid.UUID    `json:"referrer_id"`
	ReferralType ReferralType `json:"referral_type"`
}

// 1-LEVEL ONLY: stores the direct referrer for a referee. PK on referee_id => at most one referrer.
func (q *Queries) CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error) {
	row := q.db.QueryRow(ctx, createReferral, arg.RefereeID, arg.ReferrerID, arg.ReferralType)
	var i Referral
	err := row.Scan(
		&i.RefereeID,
		&i.ReferrerID,
		&i.ReferralType,
		&i.CreatedAt,
	)
	return i, err
}

const isReferredByAdmin = `-- name: IsReferredByAdmin :one
SELECT EXISTS (
    SELECT 1 FROM referrals r
    JOIN users u ON u.id = r.referrer_id
    WHERE r.referee_id = $1 AND u.role = 'admin'
)::boolean AS is_admin_referred
`

// Whitelist check for early-bird tiers: true iff this user's direct referrer is an admin.
func (q *Queries) IsReferredByAdmin(ctx context.Context, refereeID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isReferredByAdmin, refereeID)
	var is_admin_referred bool
	err := row.Scan(&is_admin_referred)
	return is_admin_referred, err
}

const getReferralByReferee = `-- name: GetReferralByReferee :one
SELECT referee_id, referrer_id, referral_type, created_at FROM referrals WHERE referee_id = $1
`

func (q *Queries) GetReferralByReferee(ctx context.Context, refereeID uuid.UUID) (Referral, error) {
	row := q.db.QueryRow(ctx, getReferralByReferee, refereeID)
	var i Referral
	err := row.Scan(
		&i.RefereeID,
		&i.ReferrerID,
		&i.ReferralType,
		&i.CreatedAt,
	)
	return i, err
}

const listCommissionsByReferrer = `-- name: ListCommissionsByReferrer :many
SELECT id, referral_id, investment_id, base_amount, rate, amount, tax_pit, net_amount, status, approved_by, paid_at, created_at, level, beneficiary_id FROM commissions WHERE beneficiary_id = $1 ORDER BY created_at DESC
`

// All commissions EARNED by a user across every level (F1/F2/F3) — keyed by beneficiary_id.
func (q *Queries) ListCommissionsByReferrer(ctx context.Context, beneficiaryID uuid.UUID) ([]Commission, error) {
	rows, err := q.db.Query(ctx, listCommissionsByReferrer, beneficiaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commission{}
	for rows.Next() {
		var i Commission
		if err := rows.Scan(
			&i.ID,
			&i.ReferralID,
			&i.InvestmentID,
			&i.BaseAmount,
			&i.Rate,
			&i.Amount,
			&i.TaxPit,
			&i.NetAmount,
			&i.Status,
			&i.ApprovedBy,
			&i.PaidAt,
			&i.CreatedAt,
			&i.Level,
			&i.BeneficiaryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferralsByReferrer = `-- name: ListReferralsByReferrer :many
SELECT referee_id, referrer_id, referral_type, created_at FROM referrals WHERE referrer_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReferralsByReferrer(ctx context.Context, referrerID uuid.UUID) ([]Referral, error) {
	rows, err := q.db.Query(ctx, listReferralsByReferrer, referrerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Referral{}
	for rows.Next() {
		var i Referral
		if err := rows.Scan(
			&i.RefereeID,
			&i.ReferrerID,
			&i.ReferralType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payCommission = `-- name: PayCommission :one
UPDATE commissions SET status = 'paid', paid_at = now() WHERE id = $1 AND status = 'approved'
RETURNING id, referral_id, investment_id, base_amount, rate, amount, tax_pit, net_amount, status, approved_by, paid_at, created_at, level, beneficiary_id
`

func (q *Queries) PayCommission(ctx context.Context, id uuid.UUID) (Commission, error) {
	row := q.db.QueryRow(ctx, payCommission, id)
	var i Commission
	err := row.Scan(
		&i.ID,
		&i.ReferralID,
		&i.InvestmentID,
		&i.BaseAmount,
		&i.Rate,
		&i.Amount,
		&i.TaxPit,
		&i.NetAmount,
		&i.Status,
		&i.ApprovedBy,
		&i.PaidAt,
		&i.CreatedAt,
		&i.Level,
		&i.BeneficiaryID,
	)
	return i, err
}

const sumCommissionEarnedByReferrer = `-- name: SumCommissionEarnedByReferrer :one
SELECT COALESCE(SUM(net_amount), 0)::bigint AS total
FROM commissions
WHERE beneficiary_id = $1 AND status <> 'rejected'
`

// Tổng hoa hồng (net) khả dụng của 1 người (mọi cấp F1/F2/F3, mọi trạng thái trừ rejected) — số dư ví.
// Cộng vào ví ngay; điểm kiểm soát là khâu DUYỆT RÚT TIỀN của admin.
func (q *Queries) SumCommissionEarnedByReferrer(ctx context.Context, beneficiaryID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumCommissionEarnedByReferrer, beneficiaryID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumPendingCommissionByBeneficiary = `-- name: SumPendingCommissionByBeneficiary :one
SELECT COALESCE(SUM(net_amount), 0)::bigint AS total
FROM commissions
WHERE beneficiary_id = $1 AND status = 'pending'
`

// Hoa hồng (net) CHƯA DUYỆT của 1 người — phần đang chờ admin duyệt (đã gộp trong số dư khả dụng).
func (q *Queries) SumPendingCommissionByBeneficiary(ctx context.Context, beneficiaryID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumPendingCommissionByBeneficiary, beneficiaryID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumCommissionsByType = `-- name: SumCommissionsByType :one
SELECT
    COALESCE(SUM(c.amount), 0)::bigint AS gross,
    COALESCE(SUM(c.tax_pit), 0)::bigint AS tax,
    COALESCE(SUM(c.net_amount), 0)::bigint AS net
FROM commissions c
JOIN referrals r ON r.referee_id = c.referral_id
WHERE r.referral_type = $1
`

type SumCommissionsByTypeRow struct {
	Gross int64 `json:"gross"`
	Tax   int64 `json:"tax"`
	Net   int64 `json:"net"`
}

func (q *Queries) SumCommissionsByType(ctx context.Context, referralType ReferralType) (SumCommissionsByTypeRow, error) {
	row := q.db.QueryRow(ctx, sumCommissionsByType, referralType)
	var i SumCommissionsByTypeRow
	err := row.Scan(&i.Gross, &i.Tax, &i.Net)
	return i, err
}
