// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO early_reservations (user_id, tier_id, amount_vnd, shares, ownership_pct)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, tier_id) DO NOTHING
RETURNING id, user_id, tier_id, amount_vnd, shares, ownership_pct, status, created_at, updated_at
`

type CreateReservationParams struct {
	UserID       uuid.UUID `json:"user_id"`
	TierID       uuid.UUID `json:"tier_id"`
	AmountVnd    int64     `json:"amount_vnd"`
	Shares       int64     `json:"shares"`
	OwnershipPct float64   `json:"ownership_pct"`
}

// Early-bird reservation: record-only. Re-reserving the same (user, tier) is idempotent.
func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (EarlyReservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.UserID,
		arg.TierID,
		arg.AmountVnd,
		arg.Shares,
		arg.OwnershipPct,
	)
	var i EarlyReservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierID,
		&i.AmountVnd,
		&i.Shares,
		&i.OwnershipPct,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByUserTier = `-- name: GetReservationByUserTier :one
SELECT id, user_id, tier_id, amount_vnd, shares, ownership_pct, status, created_at, updated_at FROM early_reservations WHERE user_id = $1 AND tier_id = $2
`

type GetReservationByUserTierParams struct {
	UserID uuid.UUID `json:"user_id"`
	TierID uuid.UUID `json:"tier_id"`
}

func (q *Queries) GetReservationByUserTier(ctx context.Context, arg GetReservationByUserTierParams) (EarlyReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByUserTier, arg.UserID, arg.TierID)
	var i EarlyReservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierID,
		&i.AmountVnd,
		&i.Shares,
		&i.OwnershipPct,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllReservations = `-- name: ListAllReservations :many
SELECT r.id, r.user_id, r.tier_id, r.amount_vnd, r.shares, r.ownership_pct, r.status, r.created_at, r.updated_at, t.name AS tier_name, u.full_name, u.email
FROM early_reservations r
JOIN investment_tiers t ON t.id = r.tier_id
JOIN users u ON u.id = r.user_id
ORDER BY r.created_at DESC
`

type ListAllReservationsRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	TierID       uuid.UUID          `json:"tier_id"`
	AmountVnd    int64              `json:"amount_vnd"`
	Shares       int64              `json:"shares"`
	OwnershipPct float64            `json:"ownership_pct"`
	Status       ReservationStatus  `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TierName     string             `json:"tier_name"`
	FullName     string             `json:"full_name"`
	Email        string             `json:"email"`
}

func (q *Queries) ListAllReservations(ctx context.Context) ([]ListAllReservationsRow, error) {
	rows, err := q.db.Query(ctx, listAllReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllReservationsRow{}
	for rows.Next() {
		var i ListAllReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TierID,
			&i.AmountVnd,
			&i.Shares,
			&i.OwnershipPct,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TierName,
			&i.FullName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByUser = `-- name: ListReservationsByUser :many
SELECT r.id, r.user_id, r.tier_id, r.amount_vnd, r.shares, r.ownership_pct, r.status, r.created_at, r.updated_at, t.name AS tier_name
FROM early_reservations r
JOIN investment_tiers t ON t.id = r.tier_id
WHERE r.user_id = $1
ORDER BY r.created_at DESC
`

type ListReservationsByUserRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	TierID       uuid.UUID          `json:"tier_id"`
	AmountVnd    int64              `json:"amount_vnd"`
	Shares       int64              `json:"shares"`
	OwnershipPct float64            `json:"ownership_pct"`
	Status       ReservationStatus  `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TierName     string             `json:"tier_name"`
}

func (q *Queries) ListReservationsByUser(ctx context.Context, userID uuid.UUID) ([]ListReservationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listReservationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReservationsByUserRow{}
	for rows.Next() {
		var i ListReservationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TierID,
			&i.AmountVnd,
			&i.Shares,
			&i.OwnershipPct,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReservationStatus = `-- name: SetReservationStatus :one
UPDATE early_reservations SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, tier_id, amount_vnd, shares, ownership_pct, status, created_at, updated_at
`

type SetReservationStatusParams struct {
	ID     uuid.UUID         `json:"id"`
	Status ReservationStatus `json:"status"`
}

func (q *Queries) SetReservationStatus(ctx context.Context, arg SetReservationStatusParams) (EarlyReservation, error) {
	row := q.db.QueryRow(ctx, setReservationStatus, arg.ID, arg.Status)
	var i EarlyReservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierID,
		&i.AmountVnd,
		&i.Shares,
		&i.OwnershipPct,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
