// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const capTable = `-- name: CapTable :many
SELECT s.user_id, u.full_name, u.email, s.shares, s.ownership_pct
FROM shareholdings s
JOIN users u ON u.id = s.user_id
WHERE s.shares > 0
ORDER BY s.shares DESC
`

type CapTableRow struct {
	UserID       uuid.UUID `json:"user_id"`
	FullName     string    `json:"full_name"`
	Email        string    `json:"email"`
	Shares       int64     `json:"shares"`
	OwnershipPct float64   `json:"ownership_pct"`
}

func (q *Queries) CapTable(ctx context.Context) ([]CapTableRow, error) {
	rows, err := q.db.Query(ctx, capTable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CapTableRow{}
	for rows.Next() {
		var i CapTableRow
		if err := rows.Scan(
			&i.UserID,
			&i.FullName,
			&i.Email,
			&i.Shares,
			&i.OwnershipPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShareholding = `-- name: GetShareholding :one
SELECT user_id, shares, ownership_pct, updated_at FROM shareholdings WHERE user_id = $1
`

func (q *Queries) GetShareholding(ctx context.Context, userID uuid.UUID) (Shareholding, error) {
	row := q.db.QueryRow(ctx, getShareholding, userID)
	var i Shareholding
	err := row.Scan(
		&i.UserID,
		&i.Shares,
		&i.OwnershipPct,
		&i.UpdatedAt,
	)
	return i, err
}

const insertShareLedger = `-- name: InsertShareLedger :one
INSERT INTO share_ledger (user_id, investment_id, shares_delta, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, investment_id, shares_delta, reason, created_at
`

type InsertShareLedgerParams struct {
	UserID       uuid.UUID     `json:"user_id"`
	InvestmentID uuid.NullUUID `json:"investment_id"`
	SharesDelta  int64         `json:"shares_delta"`
	Reason       string        `json:"reason"`
}

func (q *Queries) InsertShareLedger(ctx context.Context, arg InsertShareLedgerParams) (ShareLedger, error) {
	row := q.db.QueryRow(ctx, insertShareLedger,
		arg.UserID,
		arg.InvestmentID,
		arg.SharesDelta,
		arg.Reason,
	)
	var i ShareLedger
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvestmentID,
		&i.SharesDelta,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAccounts = `-- name: ListActiveAccounts :many
SELECT sh.user_id,
       sh.shares,
       COALESCE(SUM(i.amount_vnd) FILTER (WHERE i.status = 'approved'), 0)::bigint AS invested_vnd
FROM shareholdings sh
LEFT JOIN investments i ON i.user_id = sh.user_id
WHERE sh.shares > 0
GROUP BY sh.user_id, sh.shares
`

type ListActiveAccountsRow struct {
	UserID      uuid.UUID `json:"user_id"`
	Shares      int64     `json:"shares"`
	InvestedVnd int64     `json:"invested_vnd"`
}

// Active shareholders with their TRUE invested capital (sum of approved investments) — the basis
// for the tiered bonus banding. invested_vnd uses amount_vnd, not shares×price, so a 50tr package
// bands exactly on the 50tr boundary rather than 49.5tr.
func (q *Queries) ListActiveAccounts(ctx context.Context) ([]ListActiveAccountsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAccountsRow{}
	for rows.Next() {
		var i ListActiveAccountsRow
		if err := rows.Scan(&i.UserID, &i.Shares, &i.InvestedVnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllShareholdings = `-- name: ListAllShareholdings :many
SELECT user_id, shares, ownership_pct, updated_at FROM shareholdings WHERE shares > 0
`

func (q *Queries) ListAllShareholdings(ctx context.Context) ([]Shareholding, error) {
	rows, err := q.db.Query(ctx, listAllShareholdings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shareholding{}
	for rows.Next() {
		var i Shareholding
		if err := rows.Scan(
			&i.UserID,
			&i.Shares,
			&i.OwnershipPct,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setShareholdingPct = `-- name: SetShareholdingPct :exec
UPDATE shareholdings SET ownership_pct = $2, updated_at = now() WHERE user_id = $1
`

type SetShareholdingPctParams struct {
	UserID       uuid.UUID `json:"user_id"`
	OwnershipPct float64   `json:"ownership_pct"`
}

func (q *Queries) SetShareholdingPct(ctx context.Context, arg SetShareholdingPctParams) error {
	_, err := q.db.Exec(ctx, setShareholdingPct, arg.UserID, arg.OwnershipPct)
	return err
}

const sumLedgerByUser = `-- name: SumLedgerByUser :one
SELECT COALESCE(SUM(shares_delta), 0)::bigint AS total FROM share_ledger WHERE user_id = $1
`

// INVARIANT 4: reconcile shareholdings against the append-only ledger at any time.
func (q *Queries) SumLedgerByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumLedgerByUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const upsertShareholding = `-- name: UpsertShareholding :one
INSERT INTO shareholdings (user_id, shares, ownership_pct, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE
SET shares = shareholdings.shares + EXCLUDED.shares,
    ownership_pct = $3,
    updated_at = now()
RETURNING user_id, shares, ownership_pct, updated_at
`

type UpsertShareholdingParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Shares       int64     `json:"shares"`
	OwnershipPct float64   `json:"ownership_pct"`
}

// Keeps the read model in lock-step with the ledger inside the issuing tx.
func (q *Queries) UpsertShareholding(ctx context.Context, arg UpsertShareholdingParams) (Shareholding, error) {
	row := q.db.QueryRow(ctx, upsertShareholding, arg.UserID, arg.Shares, arg.OwnershipPct)
	var i Shareholding
	err := row.Scan(
		&i.UserID,
		&i.Shares,
		&i.OwnershipPct,
		&i.UpdatedAt,
	)
	return i, err
}
