// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
)

const adminStats = `-- name: AdminStats :one
SELECT
    (SELECT COALESCE(SUM(amount_vnd),0)::bigint FROM investments WHERE status = 'approved') AS total_capital_reconciled,
    (SELECT count(*) FROM shareholdings WHERE shares > 0)                                   AS shareholder_count,
    (SELECT shares_sold FROM offering WHERE status = 'open' ORDER BY created_at LIMIT 1)    AS shares_sold,
    (SELECT shares_for_sale FROM offering WHERE status = 'open' ORDER BY created_at LIMIT 1) AS shares_for_sale
`

type AdminStatsRow struct {
	TotalCapitalReconciled int64 `json:"total_capital_reconciled"`
	ShareholderCount       int64 `json:"shareholder_count"`
	SharesSold             int64 `json:"shares_sold"`
	SharesForSale          int64 `json:"shares_for_sale"`
}

func (q *Queries) AdminStats(ctx context.Context) (AdminStatsRow, error) {
	row := q.db.QueryRow(ctx, adminStats)
	var i AdminStatsRow
	err := row.Scan(
		&i.TotalCapitalReconciled,
		&i.ShareholderCount,
		&i.SharesSold,
		&i.SharesForSale,
	)
	return i, err
}
