// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (user_id, kind, content_type, path)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, kind, content_type, path, created_at
`

type CreateUploadParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Kind        string    `json:"kind"`
	ContentType string    `json:"content_type"`
	Path        string    `json:"path"`
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.UserID,
		arg.Kind,
		arg.ContentType,
		arg.Path,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ContentType,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const getUpload = `-- name: GetUpload :one
SELECT id, user_id, kind, content_type, path, created_at FROM uploads WHERE id = $1
`

func (q *Queries) GetUpload(ctx context.Context, id uuid.UUID) (Upload, error) {
	row := q.db.QueryRow(ctx, getUpload, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ContentType,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}
