// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT count(*) FROM users WHERE role = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, role UserRole) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (full_name, phone, email, password_hash, role, referral_code)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, full_name, phone, email, password_hash, role, kyc_status, kyc_message, referral_code, created_at, updated_at
`

type CreateUserParams struct {
	FullName     string   `json:"full_name"`
	Phone        string   `json:"phone"`
	Email        string   `json:"email"`
	PasswordHash string   `json:"password_hash"`
	Role         UserRole `json:"role"`
	ReferralCode string   `json:"referral_code"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.ReferralCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycStatus,
		&i.KycMessage,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureAdmin = `-- name: EnsureAdmin :one
INSERT INTO users (full_name, phone, email, password_hash, role, kyc_status, referral_code)
VALUES ($1, $2, $3, $4, 'admin', 'approved', $5)
ON CONFLICT (email) DO UPDATE SET role = 'admin'
RETURNING id, full_name, phone, email, password_hash, role, kyc_status, kyc_message, referral_code, created_at, updated_at
`

type EnsureAdminParams struct {
	FullName     string `json:"full_name"`
	Phone        string `json:"phone"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	ReferralCode string `json:"referral_code"`
}

func (q *Queries) EnsureAdmin(ctx context.Context, arg EnsureAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, ensureAdmin,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.ReferralCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycStatus,
		&i.KycMessage,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, phone, email, password_hash, role, kyc_status, kyc_message, referral_code, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycStatus,
		&i.KycMessage,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, phone, email, password_hash, role, kyc_status, kyc_message, referral_code, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycStatus,
		&i.KycMessage,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByReferralCode = `-- name: GetUserByReferralCode :one
SELECT id, full_name, phone, email, password_hash, role, kyc_status, kyc_message, referral_code, created_at, updated_at FROM users WHERE referral_code = $1
`

func (q *Queries) GetUserByReferralCode(ctx context.Context, referralCode string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByReferralCode, referralCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.KycStatus,
		&i.KycMessage,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, phone, email, role, kyc_status, referral_code, created_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID           uuid.UUID          `json:"id"`
	FullName     string             `json:"full_name"`
	Phone        string             `json:"phone"`
	Email        string             `json:"email"`
	Role         UserRole           `json:"role"`
	KycStatus    KycStatus          `json:"kyc_status"`
	ReferralCode string             `json:"referral_code"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.Role,
			&i.KycStatus,
			&i.ReferralCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserKYCStatus = `-- name: SetUserKYCStatus :exec
UPDATE users SET kyc_status = $2, updated_at = now() WHERE id = $1
`

type SetUserKYCStatusParams struct {
	ID        uuid.UUID `json:"id"`
	KycStatus KycStatus `json:"kyc_status"`
}

func (q *Queries) SetUserKYCStatus(ctx context.Context, arg SetUserKYCStatusParams) error {
	_, err := q.db.Exec(ctx, setUserKYCStatus, arg.ID, arg.KycStatus)
	return err
}

const setUserKYCResult = `-- name: SetUserKYCResult :exec
UPDATE users SET kyc_status = $2, kyc_message = $3, updated_at = now() WHERE id = $1
`

type SetUserKYCResultParams struct {
	ID         uuid.UUID `json:"id"`
	KycStatus  KycStatus `json:"kyc_status"`
	KycMessage string    `json:"kyc_message"`
}

func (q *Queries) SetUserKYCResult(ctx context.Context, arg SetUserKYCResultParams) error {
	_, err := q.db.Exec(ctx, setUserKYCResult, arg.ID, arg.KycStatus, arg.KycMessage)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const userDeletionStats = `-- name: UserDeletionStats :one
SELECT
    COALESCE((SELECT shares FROM shareholdings WHERE user_id = $1), 0)::bigint                       AS shares,
    (SELECT count(*) FROM share_ledger     WHERE user_id = $1)                                       AS ledger_rows,
    (SELECT count(*) FROM investments      WHERE user_id = $1 AND status IN ('reconciled','approved')) AS approved_investments,
    (SELECT count(*) FROM commissions      WHERE beneficiary_id = $1)                                AS commissions_as_beneficiary,
    (SELECT count(*) FROM commissions c JOIN referrals r ON r.referee_id = c.referral_id
                                        WHERE r.referrer_id = $1)                                    AS downline_commissions,
    (SELECT count(*) FROM dividend_payouts WHERE user_id = $1)                                       AS dividend_payouts,
    (SELECT count(*) FROM withdrawals      WHERE user_id = $1)                                       AS withdrawals,
    (SELECT count(*) FROM dividends        WHERE declared_by = $1)
      + (SELECT count(*) FROM revenue_distributions WHERE created_by = $1)                           AS admin_financial
`

type UserDeletionStatsRow struct {
	Shares                   int64 `json:"shares"`
	LedgerRows               int64 `json:"ledger_rows"`
	ApprovedInvestments      int64 `json:"approved_investments"`
	CommissionsAsBeneficiary int64 `json:"commissions_as_beneficiary"`
	DownlineCommissions      int64 `json:"downline_commissions"`
	DividendPayouts          int64 `json:"dividend_payouts"`
	Withdrawals              int64 `json:"withdrawals"`
	AdminFinancial           int64 `json:"admin_financial"`
}

func (q *Queries) UserDeletionStats(ctx context.Context, userID uuid.UUID) (UserDeletionStatsRow, error) {
	row := q.db.QueryRow(ctx, userDeletionStats, userID)
	var i UserDeletionStatsRow
	err := row.Scan(
		&i.Shares,
		&i.LedgerRows,
		&i.ApprovedInvestments,
		&i.CommissionsAsBeneficiary,
		&i.DownlineCommissions,
		&i.DividendPayouts,
		&i.Withdrawals,
		&i.AdminFinancial,
	)
	return i, err
}

const listUploadPathsByUser = `-- name: ListUploadPathsByUser :many
SELECT path FROM uploads WHERE user_id = $1
`

func (q *Queries) ListUploadPathsByUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUploadPathsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteInvestmentsByUser = `-- name: DeleteInvestmentsByUser :exec
DELETE FROM investments WHERE user_id = $1
`

func (q *Queries) DeleteInvestmentsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvestmentsByUser, userID)
	return err
}

const deleteOutgoingReferrals = `-- name: DeleteOutgoingReferrals :exec
DELETE FROM referrals WHERE referrer_id = $1
`

func (q *Queries) DeleteOutgoingReferrals(ctx context.Context, referrerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOutgoingReferrals, referrerID)
	return err
}

const deleteContractsByUser = `-- name: DeleteContractsByUser :exec
DELETE FROM contracts WHERE user_id = $1
`

func (q *Queries) DeleteContractsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContractsByUser, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const disableShareLedgerImmutability = `-- name: DisableShareLedgerImmutability :exec
ALTER TABLE share_ledger DISABLE TRIGGER USER
`

func (q *Queries) DisableShareLedgerImmutability(ctx context.Context) error {
	_, err := q.db.Exec(ctx, disableShareLedgerImmutability)
	return err
}

const enableShareLedgerImmutability = `-- name: EnableShareLedgerImmutability :exec
ALTER TABLE share_ledger ENABLE TRIGGER USER
`

func (q *Queries) EnableShareLedgerImmutability(ctx context.Context) error {
	_, err := q.db.Exec(ctx, enableShareLedgerImmutability)
	return err
}

const deleteShareLedgerByUser = `-- name: DeleteShareLedgerByUser :exec
DELETE FROM share_ledger WHERE user_id = $1
`

func (q *Queries) DeleteShareLedgerByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShareLedgerByUser, userID)
	return err
}

const deleteShareholdingByUser = `-- name: DeleteShareholdingByUser :exec
DELETE FROM shareholdings WHERE user_id = $1
`

func (q *Queries) DeleteShareholdingByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShareholdingByUser, userID)
	return err
}

const deleteDividendPayoutsByUser = `-- name: DeleteDividendPayoutsByUser :exec
DELETE FROM dividend_payouts WHERE user_id = $1
`

func (q *Queries) DeleteDividendPayoutsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDividendPayoutsByUser, userID)
	return err
}

const deleteWithdrawalsByUser = `-- name: DeleteWithdrawalsByUser :exec
DELETE FROM withdrawals WHERE user_id = $1
`

func (q *Queries) DeleteWithdrawalsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWithdrawalsByUser, userID)
	return err
}

const deleteCommissionsForInvestmentsByUser = `-- name: DeleteCommissionsForInvestmentsByUser :exec
DELETE FROM commissions
WHERE investment_id IN (SELECT id FROM investments WHERE user_id = $1)
`

func (q *Queries) DeleteCommissionsForInvestmentsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommissionsForInvestmentsByUser, userID)
	return err
}

const deleteCommissionsEarnedByReferrer = `-- name: DeleteCommissionsEarnedByReferrer :exec
DELETE FROM commissions
WHERE referral_id IN (SELECT referee_id FROM referrals WHERE referrer_id = $1)
`

func (q *Queries) DeleteCommissionsEarnedByReferrer(ctx context.Context, referrerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommissionsEarnedByReferrer, referrerID)
	return err
}

const recomputeSharesSold = `-- name: RecomputeSharesSold :exec
UPDATE offering o SET shares_sold = COALESCE((
    SELECT SUM(i.shares) FROM investments i
    JOIN investment_tiers t ON t.id = i.tier_id
    WHERE t.offering_id = o.id AND i.status = 'approved'
), 0), updated_at = now()
`

func (q *Queries) RecomputeSharesSold(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recomputeSharesSold)
	return err
}
